import PDFDocument from 'pdfkit'
import { createBrandedTablePdf, type PdfTableColumn } from '../reports/branded-table-pdf.ts'
import { receiptVerificationCode, type ReceiptVerificationData } from './fine-receipt-verification.ts'

type AuditRow = {
  id: string; userName: string; schoolId: string; type: string; title: string; reason: string
  assessed: number; paid: number; adjusted: number; balance: number; status: string; occurredAt: unknown
  receipts: Array<{ receiptNumber: string; verificationCode: string; status: string }>
}

type Receipt = ReceiptVerificationData & {
  documentLabel?: string
  status: string; paymentMethod: string
  receivedBy: string; reversedBy: string | null; reversedAt: unknown; reversalReason: string | null; notes: string | null
  student: { name: string; schoolId: string }
  allocations: Array<{ type: string; title: string; assessed: number; paid: number; balanceBefore: number; balanceAfter: number }>
  verificationCode?: string
}

function money(value: number) { return `PHP ${value.toFixed(2)}` }
function timestamp(value: unknown) {
  const date = new Date(String(value)); return Number.isNaN(date.getTime()) ? String(value ?? '') : date.toLocaleString('en-PH', { timeZone: 'Asia/Manila', dateStyle: 'medium', timeStyle: 'short' })
}

async function* rows(items: AuditRow[]) { for (const item of items) yield item }

export function createFineAuditPdf(items: AuditRow[], context: { label: string; generatedBy: string; assessed: number; collected: number; outstanding: number; waived: number }) {
  const columns: Array<PdfTableColumn<AuditRow>> = [
    { key: 'id', label: 'FINE', width: 60 }, { key: 'userName', label: 'USER', width: 120 }, { key: 'schoolId', label: 'SCHOOL ID', width: 80 },
    { key: 'type', label: 'TYPE', width: 65 }, { key: 'title', label: 'BOOK / INCIDENT', width: 130 }, { key: 'reason', label: 'REASON / CALCULATION', width: 165 },
    { key: 'assessed', label: 'ASSESSED', width: 68, format: (value) => money(Number(value)) },
    { key: 'paid', label: 'PAID', width: 65, format: (value) => money(Number(value)) },
    { key: 'adjusted', label: 'WAIVED', width: 65, format: (value) => money(Number(value)) },
    { key: 'balance', label: 'BALANCE', width: 68, format: (value) => money(Number(value)) },
    { key: 'receipts', label: 'RECEIPT / VERIFICATION', width: 135, format: (_value, row) => row.receipts.length ? row.receipts.map((receipt) => `${receipt.receiptNumber}\n${receipt.verificationCode}${receipt.status === 'Reversed' ? ' (REVERSED)' : ''}`).join('\n') : '—' },
    { key: 'status', label: 'STATUS', width: 65 }, { key: 'occurredAt', label: 'DATE', width: 92, format: (value) => timestamp(value) },
  ]
  return createBrandedTablePdf(rows(items), {
    title: 'FINES AUDIT REPORT',
    subtitle: `${context.label} | Generated by ${context.generatedBy} | Assessed ${money(context.assessed)} | Collected ${money(context.collected)} | Waived ${money(context.waived)} | Outstanding ${money(context.outstanding)}`,
    emptyMessage: 'No fine records match the selected filters.', columns,
  })
}

export function createFineReceiptPdf(receipt: Receipt) {
  const document = new PDFDocument({ size: 'A4', margin: 42 })
  const blue = '#0b5ea2'; const yellow = '#FFF200'; const width = document.page.width - 84
  document.rect(0, 0, document.page.width, 94).fill(blue)
  document.fillColor('#FFFFFF').font('Helvetica-Bold').fontSize(19).text('STI ORMOC SMART LIBRARY', 42, 25)
  const legacy = receipt.documentLabel !== 'Payment Record'
  document.fillColor(yellow).fontSize(10).text(legacy ? 'OFFICIAL CASH FINE RECEIPT' : 'CASH PAYMENT RECORD — NOT A TAX INVOICE', 42, 53)
  document.fillColor('#FFFFFF').font('Helvetica').fontSize(8).text('Cash payment recorded by authorized library personnel', 42, 70)

  let y = 120
  document.fillColor(blue).font('Helvetica-Bold').fontSize(15).text(receipt.receiptNumber, 42, y)
  document.roundedRect(document.page.width - 150, y - 4, 108, 26, 8).fill(receipt.status === 'Reversed' ? yellow : '#FFFFFF').strokeColor(blue).stroke()
  document.fillColor(blue).fontSize(9).text(receipt.status === 'Reversed' ? 'REVERSED' : 'ISSUED', document.page.width - 146, y + 4, { width: 100, align: 'center' })
  y += 42

  const details: Array<[string,string]> = [
    ['Student', receipt.student.name], ['School ID', receipt.student.schoolId], ['Payment method', 'Cash'],
    ['Received', timestamp(receipt.receivedAt)], ['Received by', receipt.receivedBy], ['Verification code', receipt.verificationCode ?? receiptVerificationCode(receipt)],
  ]
  document.fontSize(9)
  details.forEach(([label,value],index) => {
    const column = index % 2; const row = Math.floor(index/2); const x = 42 + column * (width/2)
    document.fillColor(blue).font('Helvetica-Bold').text(label.toUpperCase(), x, y + row*38, { width: width/2-12 })
    document.fillColor(blue).font('Helvetica').text(value, x, y+13+row*38, { width: width/2-12 })
  })
  y += 126

  const columnWidths = [72,170,72,72,72]
  const headers = ['TYPE','BOOK / INCIDENT','BEFORE','PAID','AFTER']
  document.rect(42,y,width,28).fill(yellow).strokeColor(blue).stroke()
  let x=42; document.fillColor(blue).font('Helvetica-Bold').fontSize(8)
  headers.forEach((header,index)=>{document.text(header,x+5,y+10,{width:columnWidths[index]-10});x+=columnWidths[index]})
  y+=28
  for(const allocation of receipt.allocations){
    const values=[allocation.type,allocation.title,money(allocation.balanceBefore),money(allocation.paid),money(allocation.balanceAfter)]
    document.rect(42,y,width,38).fill('#FFFFFF').strokeColor(blue).strokeOpacity(0.25).stroke().strokeOpacity(1)
    x=42; document.fillColor(blue).font('Helvetica').fontSize(8)
    values.forEach((value,index)=>{document.text(value,x+5,y+7,{width:columnWidths[index]-10,height:27});x+=columnWidths[index]})
    y+=38
  }

  y+=18
  document.roundedRect(document.page.width-252,y,210,54,10).fill(blue)
  document.fillColor('#FFFFFF').font('Helvetica').fontSize(9).text('TOTAL CASH RECEIVED',document.page.width-235,y+11,{width:175})
  document.fillColor(yellow).font('Helvetica-Bold').fontSize(17).text(money(receipt.amountReceived),document.page.width-235,y+27,{width:175})
  y+=76
  if(receipt.notes){document.fillColor(blue).font('Helvetica-Bold').fontSize(8).text('NOTES',42,y);document.font('Helvetica').text(receipt.notes,42,y+13,{width});y+=42}
  if(receipt.status==='Reversed'){
    document.roundedRect(42,y,width,62,8).fill(yellow)
    document.fillColor(blue).font('Helvetica-Bold').fontSize(10).text(legacy ? 'RECEIPT REVERSED' : 'PAYMENT REVERSED',55,y+12)
    document.font('Helvetica').fontSize(8).text(`Reason: ${receipt.reversalReason ?? 'Not specified'} | By: ${receipt.reversedBy ?? 'Authorized staff'} | ${timestamp(receipt.reversedAt)}`,55,y+30,{width:width-26})
    y+=78
  }
  document.moveTo(42,document.page.height-92).lineTo(document.page.width-42,document.page.height-92).strokeColor(blue).strokeOpacity(0.3).stroke().strokeOpacity(1)
  document.fillColor(blue).font('Helvetica').fontSize(8).text(legacy ? 'This digital receipt is generated from the immutable SmartLib cash-payment ledger. Reprints contain the same receipt number and verification code.' : 'This payment record reflects the SmartLib cash ledger and is not a tax invoice. Reprints retain the same number and verification code.',42,document.page.height-76,{width,align:'center'})
  document.end(); return document
}
