import { getAccessToken } from '../auth/auth-storage'
export type AttendanceFilters={period:'daily'|'weekly'|'monthly'|'semester';date:string;weekStart:string;year:number;month:number;academicTermId:string;q:string;role:string;purpose:string;presence:string;page:number;limit:number}
export type AttendanceRow={id:number;visitor_name:string;school_id:string;email:string;role:string;attendance_date:string;time_in:string;time_out:string|null;purpose:string;presence:'Inside'|'Exited'}
export type AttendanceSummary={total_visits:number;unique_visitors:number;currently_inside:number;average_visit:string|null;peak_hour:string|null;purpose_breakdown:Array<{label:string;count:number}>;role_breakdown:Array<{label:string;count:number}>;range:{from:string;to:string;label:string}}
export type AttendanceAnalytics={range:{from:string;to:string;label:string};hourly:Array<{hour:number;visits:number}>;heatmap:Array<{weekday:number;hour:number;visits:number}>;daily:Array<{date:string;visits:number}>}
export type Capacity={current:number;capacity:number;available:number;percentage:number;overCapacity:boolean}
export type AttendancePass={profile:{userId:number;schoolId:string;name:string;role:string;program:string|null;section:string|null};credential:{credentialId:number;publicId:string;issuedAt:string};summary:{visitsThisMonth:number;todayCheckIn:string|null;commonPurpose:string|null};history:Array<{log_id:number;attendance_date:string;time_in:string;time_out:string|null;purpose:string;presence:'Inside'|'Exited'}>}
export type ScanResult={visitor:{userId:number;schoolId:string;name:string;role:string;program:string|null;section:string|null};openVisit:null|{log_id:number;attendance_date:string;time_in:string;reason_for_visit:string};occupancy:Capacity}
export type ScanConfirmation={duplicate?:boolean;message:string;visitor:ScanResult['visitor'];attendance:{logId:number;checkedInAt?:string;checkedOutAt?:string;purpose?:string};occupancy:Capacity}
export type AcademicTerm={academic_term_id:number;academic_year:string;term_name:string;starts_on:string;ends_on:string;is_active:number}
export type Pagination={page:number;limit:number;total:number;total_pages:number}
function params(f:AttendanceFilters){const q=new URLSearchParams({period:f.period,page:String(f.page),limit:String(f.limit)});if(f.q)q.set('q',f.q);if(f.role)q.set('role',f.role);if(f.purpose)q.set('purpose',f.purpose);if(f.presence)q.set('presence',f.presence);if(f.period==='daily'&&f.date)q.set('date',f.date);if(f.period==='weekly'&&f.weekStart)q.set('week_start',f.weekStart);if(f.period==='monthly'){q.set('year',String(f.year));q.set('month',String(f.month))}if(f.period==='semester'&&f.academicTermId)q.set('academic_term_id',f.academicTermId);return q}
function headers(accept='application/json'){const h=new Headers({Accept:accept}),token=getAccessToken();if(token)h.set('Authorization',`Bearer ${token}`);return h}
async function json<T>(url:string){const r=await fetch(url,{credentials:'include',headers:headers()});const p=await r.json() as {data?:T;message?:string;meta?:{pagination?:Pagination}};if(!r.ok)throw new Error(p.message??'Unable to load attendance data.');return{data:p.data as T,meta:p.meta}}
async function mutate<T>(url:string,method:string,body:unknown){const r=await fetch(url,{method,credentials:'include',headers:new Headers({...Object.fromEntries(headers()),'Content-Type':'application/json'}),body:JSON.stringify(body)});const p=await r.json() as {data?:T;message?:string};if(!r.ok)throw new Error(p.message??'Unable to update attendance.');return p.data as T}
async function qrBlob(download=false){const r=await fetch(`/api/v1/attendance/pass.png${download?'?download=1':''}`,{credentials:'include',headers:headers('image/png')});if(!r.ok){const p=await r.json().catch(()=>({})) as {message?:string};throw new Error(p.message??'Unable to load the attendance QR code.')}return r.blob()}
export const attendanceApi={terms:async()=> (await json<AcademicTerm[]>('/api/v1/admin/attendance/academic-terms')).data,summary:async(f:AttendanceFilters)=>(await json<AttendanceSummary>(`/api/v1/admin/attendance/summary?${params(f)}`)).data,analytics:async(f:AttendanceFilters)=>(await json<AttendanceAnalytics>(`/api/v1/admin/attendance/analytics?${params(f)}`)).data,logs:async(f:AttendanceFilters)=>{const result=await json<AttendanceRow[]>(`/api/v1/admin/attendance/logs?${params(f)}`);return{rows:result.data,pagination:result.meta?.pagination??{page:1,limit:f.limit,total:0,total_pages:0}}},capacity:async()=>(await json<Capacity>('/api/v1/admin/attendance/capacity')).data,updateCapacity:(capacity:number,reason:string)=>mutate<Capacity>('/api/v1/admin/attendance/capacity','PATCH',{capacity,reason}),myPass:async()=>(await json<AttendancePass>('/api/v1/attendance/pass')).data,passImage:()=>qrBlob(false),downloadPass:async(schoolId:string)=>{const blob=await qrBlob(true),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`STI-Library-Pass-${schoolId}.png`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)},resolveScan:(qrPayload:string)=>mutate<ScanResult>('/api/v1/admin/attendance/scan/resolve','POST',{qr_payload:qrPayload}),checkIn:(qrPayload:string,purpose:string,requestId:string)=>mutate<ScanConfirmation>('/api/v1/admin/attendance/scan/check-in','POST',{qr_payload:qrPayload,purpose,request_id:requestId}),checkOut:(qrPayload:string)=>mutate<ScanConfirmation>('/api/v1/admin/attendance/scan/check-out','POST',{qr_payload:qrPayload}),downloadPdf:async(f:AttendanceFilters)=>{const r=await fetch(`/api/v1/admin/attendance/report.pdf?${params(f)}`,{credentials:'include',headers:headers('application/pdf')});if(!r.ok){const p=await r.json().catch(()=>({})) as {message?:string};throw new Error(p.message??'Unable to generate attendance report.')}if(!(r.headers.get('content-type')??'').includes('application/pdf'))throw new Error('The server returned an invalid report file.');const b=await r.blob(),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=`smartlib-attendance-${f.period}.pdf`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}}
