import type { Pool, RowDataPacket } from 'mysql2/promise'
import { db } from '../../config/db.js'
import { currentDate, formatDate, isPostgres } from '../../config/sql-dialect.js'
import { HttpError } from '../../core/http-error.ts'
import type { AttendanceFilters } from './attendance.validation.ts'
export type AttendanceRange={from:string;to:string;label:string}
type TermRow=RowDataPacket&{academic_term_id:number;academic_year:string;term_name:string;starts_on:string;ends_on:string;is_active:number}
function manilaToday(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Manila',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function plusDays(value:string,days:number){const date=new Date(`${value}T00:00:00+08:00`);date.setUTCDate(date.getUTCDate()+days);return date.toISOString().slice(0,10)}

const dateYmd = (expr: string) => formatDate(expr, '%Y-%m-%d', 'YYYY-MM-DD')
const timeAmpm = (expr: string) => (isPostgres
  ? `to_char(${expr}, 'HH12:MI AM')`
  : `TIME_FORMAT(${expr},'%h:%i %p')`)
const averageVisitSql = isPostgres
  ? `to_char((AVG(CASE WHEN al.time_out IS NOT NULL THEN EXTRACT(EPOCH FROM (al.time_out - al.time_in)) END) * INTERVAL '1 second'), 'HH24:MI')`
  : `DATE_FORMAT(SEC_TO_TIME(FLOOR(AVG(CASE WHEN al.time_out IS NOT NULL THEN TIME_TO_SEC(TIMEDIFF(al.time_out,al.time_in)) END))),'%H:%i')`
// Preserve MAIN's COALESCE(al.checked_in_at, <attendance_date + time_in>) precedence when deriving the visit hour.
const checkinTimestamp = isPostgres
  ? `COALESCE(al.checked_in_at,(al.attendance_date + al.time_in))`
  : `COALESCE(al.checked_in_at,TIMESTAMP(al.attendance_date,al.time_in))`
const hourOfDay = isPostgres ? `EXTRACT(HOUR FROM ${checkinTimestamp})` : `HOUR(${checkinTimestamp})`
// MySQL WEEKDAY() is Monday=0..Sunday=6; Postgres ISODOW is Monday=1..Sunday=7.
const weekdayOfDate = isPostgres ? `(EXTRACT(ISODOW FROM al.attendance_date) - 1)` : `WEEKDAY(al.attendance_date)`

export class AttendanceRepository{
 private readonly pool:Pool
 constructor(pool:Pool=db){this.pool=pool}
 async terms(){const[rows]=await this.pool.execute<TermRow[]>(`SELECT academic_term_id,academic_year,term_name,${dateYmd('starts_on')} starts_on,${dateYmd('ends_on')} ends_on,is_active FROM academic_terms ORDER BY starts_on DESC`);return rows}
 async range(f:AttendanceFilters):Promise<AttendanceRange>{if(f.period==='semester'){const[rows]=await this.pool.execute<TermRow[]>(`SELECT academic_year,term_name,${dateYmd('starts_on')} starts_on,${dateYmd('ends_on')} ends_on FROM academic_terms WHERE academic_term_id=? LIMIT 1`,[Number(f.academicTermId)]);if(!rows[0])throw new HttpError(422,'ACADEMIC_TERM_NOT_FOUND','The selected academic term does not exist.');return{from:rows[0].starts_on,to:rows[0].ends_on,label:`${rows[0].term_name}, ${rows[0].academic_year}`}}if(f.period==='monthly'){const from=`${f.year}-${String(f.month).padStart(2,'0')}-01`,next=f.month===12?`${f.year!+1}-01-01`:`${f.year}-${String(f.month!+1).padStart(2,'0')}-01`;return{from,to:plusDays(next,-1),label:from.slice(0,7)}}if(f.period==='weekly'){const from=f.weekStart??manilaToday();return{from,to:plusDays(from,6),label:`${from} to ${plusDays(from,6)}`}}const date=f.date??manilaToday();return{from:date,to:date,label:date}}
 private where(f:AttendanceFilters,r:AttendanceRange){const clauses=['al.attendance_date BETWEEN ? AND ?'];const values:Array<string|number>=[r.from,r.to];if(f.q){clauses.push('(u.full_name LIKE ? OR u.school_id LIKE ? OR u.email LIKE ?)');const q=`%${f.q}%`;values.push(q,q,q)}if(f.role){clauses.push('u.user_role=?');values.push(f.role)}if(f.purpose){clauses.push('al.reason_for_visit=?');values.push(f.purpose)}if(f.presence==='inside')clauses.push('al.time_out IS NULL');if(f.presence==='exited')clauses.push('al.time_out IS NOT NULL');return{sql:clauses.join(' AND '),values}}
 async summary(f:AttendanceFilters,r:AttendanceRange):Promise<Record<string,unknown>&{total_visits:number;unique_visitors:number}>{const w=this.where(f,r);const[rows]=await this.pool.execute<RowDataPacket[]>(`SELECT COUNT(*) total_visits,COUNT(DISTINCT al.user_id) unique_visitors,SUM(CASE WHEN al.attendance_date=${currentDate()} AND al.time_out IS NULL THEN 1 ELSE 0 END) currently_inside,${averageVisitSql} average_visit FROM attendance_logs al JOIN users u ON u.user_id=al.user_id WHERE ${w.sql}`,w.values);const[peak]=await this.pool.execute<RowDataPacket[]>(`SELECT ${hourOfDay} hour_of_day,COUNT(*) visits FROM attendance_logs al JOIN users u ON u.user_id=al.user_id WHERE ${w.sql} GROUP BY hour_of_day ORDER BY visits DESC,hour_of_day ASC LIMIT 1`,w.values);const hour=peak[0]?Number(peak[0].hour_of_day):null,peakHour=hour===null?null:`${hour%12||12}:00 ${hour<12?'AM':'PM'}`;const[purpose]=await this.pool.execute<RowDataPacket[]>(`SELECT al.reason_for_visit label,COUNT(*) count FROM attendance_logs al JOIN users u ON u.user_id=al.user_id WHERE ${w.sql} GROUP BY al.reason_for_visit ORDER BY count DESC`,w.values);const[roles]=await this.pool.execute<RowDataPacket[]>(`SELECT u.user_role label,COUNT(*) count FROM attendance_logs al JOIN users u ON u.user_id=al.user_id WHERE ${w.sql} GROUP BY u.user_role ORDER BY count DESC`,w.values);const[profile]=await this.pool.execute<RowDataPacket[]>('SELECT seat_capacity FROM library_profile_settings WHERE settings_id=1');const capacity=Number(profile[0]?.seat_capacity??80),current=Number(rows[0]?.currently_inside??0);return{...rows[0],peak_hour:peakHour,total_visits:Number(rows[0]?.total_visits??0),unique_visitors:Number(rows[0]?.unique_visitors??0),currently_inside:current,capacity,available_spaces:Math.max(0,capacity-current),occupancy_percentage:capacity?Math.round(current/capacity*100):0,over_capacity:current>capacity,purpose_breakdown:purpose,role_breakdown:roles,range:r}}
 async analytics(f:AttendanceFilters,r:AttendanceRange){const w=this.where(f,r);const[hourly]=await this.pool.execute<RowDataPacket[]>(`SELECT ${hourOfDay} hour_of_day,COUNT(*) visits FROM attendance_logs al JOIN users u ON u.user_id=al.user_id WHERE ${w.sql} GROUP BY hour_of_day ORDER BY hour_of_day`,w.values);const[heatmap]=await this.pool.execute<RowDataPacket[]>(`SELECT ${weekdayOfDate} weekday,${hourOfDay} hour_of_day,COUNT(*) visits FROM attendance_logs al JOIN users u ON u.user_id=al.user_id WHERE ${w.sql} GROUP BY weekday,hour_of_day ORDER BY weekday,hour_of_day`,w.values);const[daily]=await this.pool.execute<RowDataPacket[]>(`SELECT ${dateYmd('al.attendance_date')} attendance_date,COUNT(*) visits FROM attendance_logs al JOIN users u ON u.user_id=al.user_id WHERE ${w.sql} GROUP BY al.attendance_date ORDER BY al.attendance_date`,w.values);return{range:r,hourly:hourly.map(x=>({hour:Number(x.hour_of_day),visits:Number(x.visits)})),heatmap:heatmap.map(x=>({weekday:Number(x.weekday),hour:Number(x.hour_of_day),visits:Number(x.visits)})),daily:daily.map(x=>({date:String(x.attendance_date),visits:Number(x.visits)}))}}
 async logs(f:AttendanceFilters,r:AttendanceRange){const w=this.where(f,r),offset=(f.page-1)*f.limit,base=`FROM attendance_logs al JOIN users u ON u.user_id=al.user_id WHERE ${w.sql}`;const[countRows]=await this.pool.execute<RowDataPacket[]>(`SELECT COUNT(*) total ${base}`,w.values);const[rows]=await this.pool.execute<RowDataPacket[]>(`SELECT al.log_id id,u.full_name visitor_name,u.school_id,u.email,u.user_role role,${dateYmd('al.attendance_date')} attendance_date,${timeAmpm('al.time_in')} time_in,CASE WHEN al.time_out IS NULL THEN NULL ELSE ${timeAmpm('al.time_out')} END time_out,al.reason_for_visit purpose,CASE WHEN al.time_out IS NULL THEN 'Inside' ELSE 'Exited' END presence ${base} ORDER BY al.attendance_date DESC,al.time_in DESC LIMIT ${f.limit} OFFSET ${offset}`,w.values);const total=Number(countRows[0]?.total??0);return{rows,pagination:{page:f.page,limit:f.limit,total,total_pages:Math.ceil(total/f.limit)}}}
 async*reportRows(f:AttendanceFilters,r:AttendanceRange){let page=1;while(true){const result=await this.logs({...f,page,limit:100},r);for(const row of result.rows)yield row;if(page>=result.pagination.total_pages)break;page+=1}}
}
export const attendanceRepository=new AttendanceRepository()
