#!/usr/bin/env python3
"""
Convert MySQL 5.6-style DDL toward Postgres for Supabase drafts.

Usage (repo root):
  python tools/ai/mysql_to_pg.py database/mysql56-schema.sql -o database/supabase/001_from_baseline.sql
  python tools/ai/mysql_to_pg.py --migrations -o database/supabase/002_from_migrations.sql
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def strip_mysql_session(sql: str) -> str:
    sql = re.sub(r"(?im)^SET\s+NAMES\s+.+;?\s*$", "", sql)
    sql = re.sub(r"(?im)^SET\s+SQL_MODE\s*=.+;?\s*$", "", sql)
    sql = re.sub(r"(?is)CREATE\s+DATABASE\b.*?;", "", sql)
    sql = re.sub(r"(?im)^USE\s+.+;?\s*$", "", sql)
    sql = re.sub(r"(?im)^DELIMITER\s+.+;?\s*$", "", sql)
    sql = re.sub(r"(?im)^\s*DEFAULT\s+CHARACTER\s+SET\s+.+;?\s*$", "", sql)
    sql = re.sub(r"(?im)^\s*DEFAULT\s+COLLATE\s+.+;?\s*$", "", sql)
    return sql


def extract_indexes(create_body: str, table: str) -> tuple[str, list[str]]:
    """Remove inline KEY clauses; return cleaned body + CREATE INDEX statements."""
    indexes: list[str] = []
    pattern = re.compile(r",?\s*\bKEY\s+(\w+)\s*\(", re.IGNORECASE)
    while True:
        match = pattern.search(create_body)
        if not match:
            break
        start = match.end()
        depth = 1
        i = start
        while i < len(create_body) and depth:
            if create_body[i] == "(":
                depth += 1
            elif create_body[i] == ")":
                depth -= 1
            i += 1
        cols = re.sub(r"(\w+)\(\d+\)", r"\1", create_body[start : i - 1])
        indexes.append(f"CREATE INDEX IF NOT EXISTS {match.group(1)} ON {table} ({cols});")
        create_body = create_body[: match.start()] + create_body[i:]
    create_body = re.sub(r",\s*,+", ",", create_body)
    create_body = re.sub(r",\s*\)", ")", create_body)
    return create_body, indexes


def convert_create_tables(sql: str) -> str:
    indexes_all: list[str] = []

    def table_repl(match: re.Match[str]) -> str:
        table = match.group(1)
        body = match.group(2)
        body, indexes = extract_indexes(body, table)
        indexes_all.extend(indexes)
        return f"CREATE TABLE IF NOT EXISTS {table} ({body});"

    sql = re.sub(
        r"CREATE TABLE IF NOT EXISTS\s+(\w+)\s*\((.*?)\)\s*;",
        table_repl,
        sql,
        flags=re.IGNORECASE | re.DOTALL,
    )
    if indexes_all:
        sql += "\n\n-- Recreated indexes\n" + "\n".join(indexes_all) + "\n"
    return sql


def convert_types(sql: str) -> str:
    sql = sql.replace("`", "")
    sql = re.sub(r"\)\s*ENGINE=InnoDB[^;]*;", ");", sql, flags=re.IGNORECASE)
    sql = re.sub(r"\bTINYINT\s*\(\s*1\s*\)", "SMALLINT", sql, flags=re.IGNORECASE)
    sql = re.sub(r"\bTINYINT\s+UNSIGNED\b", "SMALLINT", sql, flags=re.IGNORECASE)
    sql = re.sub(r"\bSMALLINT\s+UNSIGNED\b", "INTEGER", sql, flags=re.IGNORECASE)
    sql = re.sub(r"\bINT\s+UNSIGNED\b", "INTEGER", sql, flags=re.IGNORECASE)
    sql = re.sub(r"\bBIGINT\s+UNSIGNED\b", "BIGINT", sql, flags=re.IGNORECASE)
    sql = re.sub(
        r"\bBIGINT\s+NOT\s+NULL\s+AUTO_INCREMENT\b",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY",
        sql,
        flags=re.IGNORECASE,
    )
    sql = re.sub(
        r"\bINT(?:EGER)?\s+NOT\s+NULL\s+AUTO_INCREMENT\b",
        "INTEGER GENERATED BY DEFAULT AS IDENTITY",
        sql,
        flags=re.IGNORECASE,
    )
    sql = re.sub(
        r"\bSMALLINT\s+NOT\s+NULL\s+AUTO_INCREMENT\b",
        "SMALLINT GENERATED BY DEFAULT AS IDENTITY",
        sql,
        flags=re.IGNORECASE,
    )
    sql = re.sub(r"\bAUTO_INCREMENT\b", "", sql, flags=re.IGNORECASE)
    sql = re.sub(r"\bMEDIUMTEXT\b", "TEXT", sql, flags=re.IGNORECASE)
    sql = re.sub(r"\bLONGTEXT\b", "TEXT", sql, flags=re.IGNORECASE)
    sql = re.sub(r"\bDATETIME\b", "TIMESTAMP", sql, flags=re.IGNORECASE)
    sql = re.sub(r"\bYEAR\b(?!\s*\()", "SMALLINT", sql, flags=re.IGNORECASE)
    # ENUM → TEXT (drop enum list to avoid comma noise inside comments)
    sql = re.sub(r"\bENUM\s*\([^)]*\)", "TEXT", sql, flags=re.IGNORECASE)
    sql = re.sub(r"\bUNIQUE KEY\s+(\w+)\s*\(", r"CONSTRAINT \1 UNIQUE (", sql, flags=re.IGNORECASE)
    sql = re.sub(r"\bUNSIGNED\b", "", sql, flags=re.IGNORECASE)
    sql = re.sub(
        r"ON DUPLICATE KEY UPDATE",
        "ON CONFLICT DO UPDATE SET",
        sql,
        flags=re.IGNORECASE,
    )
    sql = re.sub(r"VALUES\((\w+)\)", r"EXCLUDED.\1", sql)
    sql = re.sub(
        r"(INSERT INTO roles\b[\s\S]*?)ON CONFLICT DO UPDATE SET",
        r"\1ON CONFLICT (role_name) DO UPDATE SET",
        sql,
        flags=re.IGNORECASE,
    )
    sql = re.sub(r"\bINSERT\s+IGNORE\s+INTO\b", "INSERT INTO", sql, flags=re.IGNORECASE)
    sql = re.sub(r"\bIFNULL\s*\(", "COALESCE(", sql, flags=re.IGNORECASE)
    sql = re.sub(
        r"CREATE\s+OR\s+REPLACE\s+ALGORITHM\s*=\s*\w+\s+DEFINER\s*=\s*`?[^`\s]+`?@`?[^`\s]+`?\s+SQL\s+SECURITY\s+\w+\s+VIEW",
        "CREATE OR REPLACE VIEW",
        sql,
        flags=re.IGNORECASE,
    )
    sql = re.sub(
        r"CREATE\s+ALGORITHM\s*=\s*\w+\s+DEFINER\s*=\s*`?[^`\s]+`?@`?[^`\s]+`?\s+SQL\s+SECURITY\s+\w+\s+VIEW",
        "CREATE VIEW",
        sql,
        flags=re.IGNORECASE,
    )
    sql = re.sub(r"\bALGORITHM\s*=\s*\w+\s*", "", sql, flags=re.IGNORECASE)
    # Drop MySQL FULLTEXT indexes (use pg trigram later if needed)
    sql = re.sub(r",?\s*FULLTEXT\s+(?:KEY\s+)?(?:\w+\s*)?\([^)]*\)", "", sql, flags=re.IGNORECASE)
    sql = re.sub(r",?\s*FULLTEXT\b", "", sql, flags=re.IGNORECASE)
    sql = re.sub(r"\s+COMMENT\s+'([^']|'')*'", "", sql, flags=re.IGNORECASE)
    sql = re.sub(r'\s+COMMENT\s+"([^"]|"")*"', "", sql, flags=re.IGNORECASE)
    # MySQL charset/engine alters are no-ops on Postgres
    sql = re.sub(
        r"ALTER\s+TABLE\s+\w+\s+ENGINE\s*=\s*\w+\s*,\s*CONVERT\s+TO\s+CHARACTER\s+SET\s+\w+\s+COLLATE\s+\w+\s*;",
        "-- skipped MySQL ENGINE/CONVERT alter\n",
        sql,
        flags=re.IGNORECASE,
    )
    sql = re.sub(
        r"ALTER\s+TABLE\s+\w+\s+CONVERT\s+TO\s+CHARACTER\s+SET\s+\w+(?:\s+COLLATE\s+\w+)?\s*;",
        "-- skipped MySQL CONVERT alter\n",
        sql,
        flags=re.IGNORECASE,
    )
    sql = re.sub(
        r"ALTER\s+TABLE\s+\w+\s+ENGINE\s*=\s*\w+\s*;",
        "-- skipped MySQL ENGINE alter\n",
        sql,
        flags=re.IGNORECASE,
    )
    return sql


def strip_forward_fks(sql: str, known_missing: set[str]) -> str:
    """Drop FK clauses that reference tables created only in later migrations."""

    def fk_repl(match: re.Match[str]) -> str:
        target = match.group(2)
        if target.lower() in known_missing:
            return ""
        return match.group(0)

    return re.sub(
        r",?\s*CONSTRAINT\s+(\w+)\s+FOREIGN KEY\s*\([^)]+\)\s*REFERENCES\s+(\w+)\s*\([^)]+\)"
        r"(?:\s+ON\s+(?:UPDATE|DELETE)\s+(?:CASCADE|RESTRICT|SET\s+NULL|SET\s+DEFAULT|NO\s+ACTION))*",
        fk_repl,
        sql,
        flags=re.IGNORECASE,
    )


FORWARD_FK_TARGETS = {
    "physical_copies",
    "titles",
    "authors",
    "research_records",
    "barcode_sequences",
    "inventory_audit_events",
    "print_pricing_rules",
    "print_status_history",
    "book_titles",
}


def comment_triggers(sql: str) -> str:
    sql = re.sub(
        r"(?is)CREATE\s+TRIGGER\b.*?\bEND\s*(?:\$\$|;)",
        lambda m: "-- TODO PL/pgSQL trigger (skipped)\n",
        sql,
    )
    sql = re.sub(r"(?im)^DROP\s+TRIGGER\b.+;?\s*$", "", sql)
    return sql


def wrap_header(body: str, source: str) -> str:
    return f"""-- ============================================================================
-- Auto-converted from {source} by tools/ai/mysql_to_pg.py
-- Review before applying to Supabase. Triggers need PL/pgSQL rewrite.
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS public;

{body.strip()}

CREATE TABLE IF NOT EXISTS schema_migrations (
  migration_name VARCHAR(191) PRIMARY KEY,
  checksum CHAR(64) NOT NULL,
  applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
"""


def convert_file(path: Path) -> str:
    source = path.read_text(encoding="utf-8")
    sql = strip_mysql_session(source)
    sql = convert_types(sql)
    sql = comment_triggers(sql)
    sql = convert_create_tables(sql)
    sql = strip_forward_fks(sql, FORWARD_FK_TARGETS)
    sql = re.sub(r",\s*,+", ",", sql)
    sql = re.sub(r",\s*\)", ")", sql)
    return sql


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path, nargs="?")
    parser.add_argument("-o", "--output", type=Path, required=True)
    parser.add_argument("--migrations", action="store_true")
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)

    if args.migrations:
        mig_dir = ROOT / "database" / "migrations"
        parts = []
        for path in sorted(mig_dir.glob("*.sql")):
            parts.append(f"\n-- ===== {path.name} =====\n")
            parts.append(convert_file(path))
        body = "\n".join(parts)
        source = "database/migrations/*.sql"
    else:
        if not args.input:
            print("input path required unless --migrations", file=sys.stderr)
            return 2
        body = convert_file(args.input)
        source = str(args.input).replace("\\", "/")

    args.output.write_text(wrap_header(body, source), encoding="utf-8")
    print(f"Wrote {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
