-- ============================================================================
-- Auto-converted from database/mysql56-schema.sql by tools/ai/mysql_to_pg.py
-- Review before applying to Supabase. Triggers need PL/pgSQL rewrite.
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS public;

-- ============================================================================
-- STI Ormoc Smart Library Management System
-- MySQL 5.6-compatible database schema
-- Engine: InnoDB | Character set: utf8
-- ============================================================================






-- ============================================================================
-- 1. USER MANAGEMENT AND STATE LIFECYCLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS roles (
  role_id SMALLINT GENERATED BY DEFAULT AS IDENTITY,
  role_name VARCHAR(50) NOT NULL,
  description VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (role_id),
  CONSTRAINT uq_roles_role_name UNIQUE (role_name)
);

INSERT INTO roles (role_name, description) VALUES
  ('System Administrator', 'Full system configuration and user-management access'),
  ('Librarian', 'Library operations, catalog, circulation, printing, and reports'),
  ('Student', 'Student catalog, borrowing, reservations, attendance, and printing access'),
  ('Faculty', 'Faculty catalog, circulation, reservations, attendance, and printing access')
ON CONFLICT (role_name) DO UPDATE SET
  description = EXCLUDED.description;

CREATE TABLE IF NOT EXISTS users (
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  role_id SMALLINT NOT NULL,
  user_role TEXT NOT NULL,
  institutional_id VARCHAR(50) NOT NULL,
  school_id VARCHAR(50) NOT NULL,
  full_name VARCHAR(150) NOT NULL,
  email VARCHAR(191) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  educational_level TEXT DEFAULT NULL,
  course_or_strand VARCHAR(150) DEFAULT NULL,
  section VARCHAR(100) DEFAULT NULL,
  account_status TEXT NOT NULL DEFAULT 'Active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT NULL,
  PRIMARY KEY (user_id),
  CONSTRAINT uq_users_institutional_id UNIQUE (institutional_id),
  CONSTRAINT uq_users_school_id UNIQUE (school_id),
  CONSTRAINT uq_users_email UNIQUE (email),
  CONSTRAINT fk_users_role
    FOREIGN KEY (role_id) REFERENCES roles (role_id)
    ON UPDATE CASCADE ON DELETE RESTRICT
);

-- Normalized authentication identity. user_id is a compatibility bridge for
-- accounts imported from the pre-normalization users table.
CREATE TABLE IF NOT EXISTS accounts (
  account_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT DEFAULT NULL,
  school_id VARCHAR(50) NOT NULL,
  contact_number VARCHAR(30) DEFAULT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role TEXT NOT NULL,
  account_status TEXT NOT NULL DEFAULT 'Active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT NULL,
  PRIMARY KEY (account_id),
  CONSTRAINT uq_accounts_school_id UNIQUE (school_id),
  CONSTRAINT uq_accounts_user_id UNIQUE (user_id),
  CONSTRAINT fk_accounts_legacy_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS student_profiles (
  student_profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  account_id BIGINT NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  program_strand VARCHAR(150) NOT NULL,
  year_grade_level VARCHAR(100) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT NULL,
  PRIMARY KEY (student_profile_id),
  CONSTRAINT uq_student_profiles_account UNIQUE (account_id),
  CONSTRAINT fk_student_profiles_account
    FOREIGN KEY (account_id) REFERENCES accounts (account_id)
    ON UPDATE CASCADE ON DELETE CASCADE
);

-- Server-side authentication sessions. Browser cookies store only an opaque ID.
CREATE TABLE IF NOT EXISTS auth_sessions (
  session_id VARCHAR(128) NOT NULL,
  session_data TEXT NOT NULL,
  expires_at BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL,
  PRIMARY KEY (session_id)
);

-- ============================================================================
-- 2. DIGITAL CATALOGING: CATEGORIES, BOOKS, AND RESEARCH MATERIALS
-- Each material row represents one individually barcoded physical item.
-- ============================================================================

CREATE TABLE IF NOT EXISTS categories (
  category_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  category_name VARCHAR(100) NOT NULL,
  shelf_location VARCHAR(100) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT NULL,
  PRIMARY KEY (category_id),
  CONSTRAINT uq_categories_name UNIQUE (category_name)
);

CREATE TABLE IF NOT EXISTS materials (
  material_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  category_id INTEGER DEFAULT NULL,
  barcode VARCHAR(100) NOT NULL,
  qr_code_data TEXT DEFAULT NULL,
  title VARCHAR(255) NOT NULL,
  author VARCHAR(255) NOT NULL,
  isbn VARCHAR(30) DEFAULT NULL,
  publication_year INTEGER DEFAULT NULL,
  shelf_location VARCHAR(100) NOT NULL,
  material_type TEXT NOT NULL DEFAULT 'Book',
  availability_status TEXT NOT NULL DEFAULT 'Available',
  department_or_program VARCHAR(150) DEFAULT NULL,
  abstract_text TEXT,
  date_added TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT NULL,
  PRIMARY KEY (material_id),
  CONSTRAINT uq_materials_barcode UNIQUE (barcode),
  CONSTRAINT fk_materials_category
    FOREIGN KEY (category_id) REFERENCES categories (category_id)
    ON UPDATE CASCADE ON DELETE SET NULL
);

-- Independent physically bound research/thesis inventory. This ledger does
-- not reference bibliographic book-title tables.
CREATE TABLE IF NOT EXISTS research_inventory (
  research_inventory_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  title VARCHAR(255) NOT NULL,
  authors TEXT NOT NULL,
  adviser VARCHAR(255) NOT NULL,
  publication_year SMALLINT NOT NULL,
  accession_number VARCHAR(100) NOT NULL,
  barcode VARCHAR(100) NOT NULL,
  condition_state TEXT NOT NULL DEFAULT 'good',
  availability_status TEXT NOT NULL DEFAULT 'available',
  lifecycle_status TEXT NOT NULL DEFAULT 'Active',
  shelf_location VARCHAR(100) NOT NULL,
  last_audited_at TIMESTAMP DEFAULT NULL,
  archived_at TIMESTAMP DEFAULT NULL,
  archive_reason VARCHAR(255) DEFAULT NULL,
  archived_by_user_id BIGINT DEFAULT NULL,
  row_version INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT NULL,
  PRIMARY KEY (research_inventory_id),
  CONSTRAINT uq_research_inventory_accession UNIQUE (accession_number),
  CONSTRAINT uq_research_inventory_barcode UNIQUE (barcode),
  CONSTRAINT fk_research_inventory_archived_by
    FOREIGN KEY (archived_by_user_id) REFERENCES users (user_id)
    ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS research_inventory_audit_events (
  research_inventory_audit_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  research_inventory_id BIGINT DEFAULT NULL,
  barcode_snapshot VARCHAR(100) NOT NULL,
  event_type TEXT NOT NULL,
  previous_condition TEXT DEFAULT NULL,
  new_condition TEXT DEFAULT NULL,
  previous_availability TEXT DEFAULT NULL,
  new_availability TEXT DEFAULT NULL,
  action_reason VARCHAR(255) DEFAULT NULL,
  performed_by_id BIGINT DEFAULT NULL,
  performed_by_label VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (research_inventory_audit_event_id),
  CONSTRAINT fk_research_inventory_audit_item
    FOREIGN KEY (research_inventory_id) REFERENCES research_inventory (research_inventory_id)
    ON UPDATE CASCADE ON DELETE SET NULL
);

-- ============================================================================
-- 3. AUTOMATED CIRCULATION AND RESERVATIONS
-- Students are limited to two simultaneous Borrowed/Overdue materials.
-- Faculty and staff roles are not limited by the database trigger.
-- ============================================================================

CREATE TABLE IF NOT EXISTS borrow_transactions (
  transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  material_id BIGINT NOT NULL,
  physical_copy_id BIGINT DEFAULT NULL,
  reservation_id BIGINT DEFAULT NULL,
  request_group_id CHAR(36) DEFAULT NULL,
  processed_by_user_id BIGINT DEFAULT NULL,
  borrowed_at TIMESTAMP DEFAULT NULL,
  due_at TIMESTAMP DEFAULT NULL,
  returned_at TIMESTAMP DEFAULT NULL,
  reported_lost_at TIMESTAMP DEFAULT NULL,
  lost_confirmed_at TIMESTAMP DEFAULT NULL,
  cancelled_at TIMESTAMP DEFAULT NULL,
  cancelled_by_user_id BIGINT DEFAULT NULL,
  cancellation_reason VARCHAR(255) DEFAULT NULL,
  transaction_status TEXT NOT NULL DEFAULT 'Pending',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT NULL,
  PRIMARY KEY (transaction_id),
  CONSTRAINT uq_borrow_reservation UNIQUE (reservation_id),
  CONSTRAINT fk_borrow_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_borrow_material
    FOREIGN KEY (material_id) REFERENCES materials (material_id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_borrow_processed_by
    FOREIGN KEY (processed_by_user_id) REFERENCES users (user_id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_borrow_cancelled_by
    FOREIGN KEY (cancelled_by_user_id) REFERENCES users (user_id)
    ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS reservations (
  reservation_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  material_id BIGINT NOT NULL,
  book_title_id BIGINT DEFAULT NULL,
  accession_id BIGINT DEFAULT NULL,
  assigned_physical_copy_id BIGINT DEFAULT NULL,
  queue_position INTEGER NOT NULL,
  reservation_status TEXT NOT NULL DEFAULT 'pending',
  reserved_at TIMESTAMP NOT NULL,
  pickup_deadline TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT NULL,
  PRIMARY KEY (reservation_id),
  CONSTRAINT fk_reservation_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_reservation_material
    FOREIGN KEY (material_id) REFERENCES materials (material_id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_reservation_accession
    FOREIGN KEY (accession_id) REFERENCES materials (material_id)
    ON UPDATE CASCADE ON DELETE SET NULL
);

ALTER TABLE borrow_transactions
  ADD CONSTRAINT fk_borrow_reservation
    FOREIGN KEY (reservation_id) REFERENCES reservations (reservation_id)
    ON UPDATE CASCADE ON DELETE SET NULL;

-- ============================================================================
-- 4. FINES AND DIGITAL CLEARANCE
-- Fine policy: PHP 2.00/hour after the 8:59 AM cutoff on the due date;
-- beginning the following day, use the PHP 10.00/day rate.
-- The service layer records the calculation inputs for auditability.
-- ============================================================================

CREATE TABLE IF NOT EXISTS fines (
  fine_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  transaction_id BIGINT DEFAULT NULL,
  user_id BIGINT NOT NULL,
  fine_type TEXT NOT NULL DEFAULT 'Overdue',
  fine_amount DECIMAL(10,2)  NOT NULL DEFAULT 0.00,
  payment_status TEXT NOT NULL DEFAULT 'Unpaid',
  calculation_basis TEXT NOT NULL DEFAULT 'Hourly',
  overdue_units INTEGER NOT NULL DEFAULT 0,
  rate_applied DECIMAL(10,2)  NOT NULL DEFAULT 2.00,
  maximum_cap_applied DECIMAL(10,2)  DEFAULT NULL,
  applied_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  finalized_at TIMESTAMP DEFAULT NULL,
  paid_at TIMESTAMP DEFAULT NULL,
  notes VARCHAR(255) DEFAULT NULL,
  updated_at TIMESTAMP DEFAULT NULL,
  PRIMARY KEY (fine_id),
  CONSTRAINT uq_fines_transaction UNIQUE (transaction_id),
  CONSTRAINT fk_fines_transaction
    FOREIGN KEY (transaction_id) REFERENCES borrow_transactions (transaction_id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_fines_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS fine_policy_versions (
  fine_policy_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  hourly_rate DECIMAL(10,2)  NOT NULL,
  daily_rate DECIMAL(10,2)  NOT NULL,
  maximum_penalty DECIMAL(10,2)  NOT NULL,
  effective_from TIMESTAMP NOT NULL,
  effective_until TIMESTAMP DEFAULT NULL,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_by_user_id BIGINT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (fine_policy_id),
  CONSTRAINT fk_fine_policy_creator FOREIGN KEY (created_by_user_id) REFERENCES users (user_id) ON UPDATE CASCADE ON DELETE SET NULL
);

INSERT INTO fine_policy_versions (hourly_rate,daily_rate,maximum_penalty,effective_from,is_active)
SELECT 2.00,10.00,500.00,'2026-01-01 00:00:00',1 WHERE NOT EXISTS (SELECT 1 FROM fine_policy_versions);

CREATE TABLE IF NOT EXISTS fine_infractions (
  fine_infraction_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  fine_id BIGINT NOT NULL,
  category VARCHAR(80) NOT NULL,
  incident_at TIMESTAMP NOT NULL,
  incident_location VARCHAR(150) DEFAULT NULL,
  details VARCHAR(500) NOT NULL,
  issued_by_user_id BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (fine_infraction_id),
  CONSTRAINT uq_fine_infraction_fine UNIQUE (fine_id),
  CONSTRAINT fk_fine_infraction_fine FOREIGN KEY (fine_id) REFERENCES fines (fine_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_fine_infraction_issuer FOREIGN KEY (issued_by_user_id) REFERENCES users (user_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS fine_payment_receipts (
  fine_payment_receipt_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  receipt_number VARCHAR(32) DEFAULT NULL,
  request_key VARCHAR(64) NOT NULL,
  user_id BIGINT NOT NULL,
  amount_received DECIMAL(10,2)  NOT NULL,
  payment_method TEXT NOT NULL DEFAULT 'Cash',
  received_by_user_id BIGINT NOT NULL,
  received_at TIMESTAMP NOT NULL,
  receipt_status TEXT NOT NULL DEFAULT 'Issued',
  reversed_by_user_id BIGINT DEFAULT NULL,
  reversed_at TIMESTAMP DEFAULT NULL,
  reversal_reason VARCHAR(500) DEFAULT NULL,
  notes VARCHAR(500) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (fine_payment_receipt_id),
  CONSTRAINT uq_fine_receipt_number UNIQUE (receipt_number),
  CONSTRAINT uq_fine_receipt_request UNIQUE (request_key),
  CONSTRAINT fk_fine_receipt_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_fine_receipt_receiver FOREIGN KEY (received_by_user_id) REFERENCES users (user_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_fine_receipt_reverser FOREIGN KEY (reversed_by_user_id) REFERENCES users (user_id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS fine_payment_allocations (
  fine_payment_allocation_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  fine_payment_receipt_id BIGINT NOT NULL,
  fine_id BIGINT DEFAULT NULL,
  lost_book_report_id BIGINT DEFAULT NULL,
  amount_allocated DECIMAL(10,2)  NOT NULL,
  balance_before DECIMAL(10,2)  NOT NULL,
  balance_after DECIMAL(10,2)  NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (fine_payment_allocation_id),
  CONSTRAINT uq_receipt_fine_allocation UNIQUE (fine_payment_receipt_id,fine_id),
  CONSTRAINT uq_receipt_lost_allocation UNIQUE (fine_payment_receipt_id,lost_book_report_id),
  CONSTRAINT fk_fine_allocation_receipt FOREIGN KEY (fine_payment_receipt_id) REFERENCES fine_payment_receipts (fine_payment_receipt_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_fine_allocation_fine FOREIGN KEY (fine_id) REFERENCES fines (fine_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS fine_adjustments (
  fine_adjustment_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  fine_id BIGINT NOT NULL,
  adjustment_type TEXT NOT NULL,
  amount_adjusted DECIMAL(10,2)  NOT NULL,
  reason VARCHAR(500) NOT NULL,
  adjusted_by_user_id BIGINT NOT NULL,
  adjusted_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (fine_adjustment_id),
  CONSTRAINT fk_fine_adjustment_fine FOREIGN KEY (fine_id) REFERENCES fines (fine_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_fine_adjustment_actor FOREIGN KEY (adjusted_by_user_id) REFERENCES users (user_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS clearance_statuses (
  clearance_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  standing_status TEXT NOT NULL DEFAULT 'Cleared',
  reason_block_details TEXT,
  reviewed_by_user_id BIGINT DEFAULT NULL,
  last_checked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT NULL,
  PRIMARY KEY (clearance_id),
  CONSTRAINT uq_clearance_user UNIQUE (user_id),
  CONSTRAINT fk_clearance_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_clearance_reviewer
    FOREIGN KEY (reviewed_by_user_id) REFERENCES users (user_id)
    ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS clearance_overrides (
  clearance_override_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  override_status TEXT NOT NULL,
  reason VARCHAR(500) NOT NULL,
  applied_by_user_id BIGINT NOT NULL,
  applied_at TIMESTAMP NOT NULL,
  expires_at TIMESTAMP DEFAULT NULL,
  revoked_by_user_id BIGINT DEFAULT NULL,
  revoked_at TIMESTAMP DEFAULT NULL,
  revocation_reason VARCHAR(500) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (clearance_override_id),
  CONSTRAINT fk_clearance_override_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_clearance_override_applier FOREIGN KEY (applied_by_user_id) REFERENCES users (user_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_clearance_override_revoker FOREIGN KEY (revoked_by_user_id) REFERENCES users (user_id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS lost_book_reports (
  lost_book_report_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  transaction_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  physical_copy_id BIGINT DEFAULT NULL,
  report_status TEXT NOT NULL DEFAULT 'Pending',
  purchase_price_snapshot DECIMAL(10,2)  DEFAULT NULL,
  replacement_charge DECIMAL(10,2)  NOT NULL DEFAULT 0.00,
  payment_status TEXT NOT NULL DEFAULT 'Unpaid',
  reported_at TIMESTAMP NOT NULL,
  verified_by_user_id BIGINT DEFAULT NULL,
  verified_at TIMESTAMP DEFAULT NULL,
  staff_notes VARCHAR(500) DEFAULT NULL,
  paid_at TIMESTAMP DEFAULT NULL,
  payment_recorded_by_user_id BIGINT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT NULL,
  PRIMARY KEY (lost_book_report_id),
  CONSTRAINT uq_lost_book_transaction UNIQUE (transaction_id),
  CONSTRAINT fk_lost_book_transaction FOREIGN KEY (transaction_id) REFERENCES borrow_transactions (transaction_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_lost_book_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_lost_book_verifier FOREIGN KEY (verified_by_user_id) REFERENCES users (user_id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_lost_book_payment_recorder FOREIGN KEY (payment_recorded_by_user_id) REFERENCES users (user_id) ON UPDATE CASCADE ON DELETE SET NULL
);

ALTER TABLE fine_payment_allocations
  ADD CONSTRAINT fk_fine_allocation_lost
    FOREIGN KEY (lost_book_report_id) REFERENCES lost_book_reports (lost_book_report_id)
    ON UPDATE CASCADE ON DELETE RESTRICT;

-- ============================================================================
-- 5. QR-BASED ATTENDANCE MONITORING
-- ============================================================================

CREATE TABLE IF NOT EXISTS academic_terms (
  academic_term_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  academic_year VARCHAR(20) NOT NULL,
  term_name VARCHAR(100) NOT NULL,
  starts_on DATE NOT NULL,
  ends_on DATE NOT NULL,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT NULL,
  PRIMARY KEY (academic_term_id),
  CONSTRAINT uq_academic_terms_name_year UNIQUE (academic_year, term_name)
);

CREATE TABLE IF NOT EXISTS attendance_logs (
  log_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  attendance_date DATE NOT NULL,
  time_in TIME NOT NULL,
  time_out TIME DEFAULT NULL,
  reason_for_visit TEXT NOT NULL,
  qr_reference VARCHAR(100) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (log_id),
  CONSTRAINT fk_attendance_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON UPDATE CASCADE ON DELETE RESTRICT
);

-- ============================================================================
-- 6. ONLINE PRINTING SERVICE REQUEST AND QUEUE
-- Store only file metadata/path here; do not store uploaded binary files.
-- ============================================================================

CREATE TABLE IF NOT EXISTS print_requests (
  request_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  processed_by_user_id BIGINT DEFAULT NULL,
  file_name VARCHAR(255) NOT NULL,
  file_path VARCHAR(500) NOT NULL,
  number_of_copies INTEGER NOT NULL DEFAULT 1,
  print_type TEXT NOT NULL DEFAULT 'Monochrome',
  optional_notes TEXT,
  calculated_cost DECIMAL(10,2)  NOT NULL DEFAULT 0.00,
  job_status TEXT NOT NULL DEFAULT 'Pending',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT NULL,
  completed_at TIMESTAMP DEFAULT NULL,
  PRIMARY KEY (request_id),
  CONSTRAINT fk_print_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_print_processed_by
    FOREIGN KEY (processed_by_user_id) REFERENCES users (user_id)
    ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS printing_service_settings (
  settings_id SMALLINT NOT NULL,
  accepting_requests INTEGER NOT NULL DEFAULT 1,
  unavailable_reason VARCHAR(255) DEFAULT NULL,
  updated_by_user_id BIGINT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT NULL,
  PRIMARY KEY (settings_id),
  CONSTRAINT fk_print_service_updated_by
    FOREIGN KEY (updated_by_user_id) REFERENCES users (user_id)
    ON UPDATE CASCADE ON DELETE SET NULL
);

INSERT INTO printing_service_settings (settings_id,accepting_requests) VALUES (1,1);

CREATE TABLE IF NOT EXISTS print_file_download_audit (
  download_audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  request_id BIGINT NOT NULL,
  downloaded_by_user_id BIGINT NOT NULL,
  downloaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  source_ip VARCHAR(45) DEFAULT NULL,
  user_agent VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (download_audit_id),
  CONSTRAINT fk_print_download_request FOREIGN KEY (request_id) REFERENCES print_requests (request_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_print_download_user FOREIGN KEY (downloaded_by_user_id) REFERENCES users (user_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

-- ============================================================================
-- 7. PRINTING SUPPLIES AND ASSET MANAGEMENT
-- Replenishment history is normalized into a child table.
-- ============================================================================

CREATE TABLE IF NOT EXISTS printers (
  printer_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  printer_name VARCHAR(100) NOT NULL,
  printer_model VARCHAR(100) DEFAULT NULL,
  location VARCHAR(100) NOT NULL,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (printer_id),
  CONSTRAINT uq_printers_name_location UNIQUE (printer_name, location)
);

CREATE TABLE IF NOT EXISTS ink_repository (
  ink_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  printer_id INTEGER DEFAULT NULL,
  cartridge_type VARCHAR(100) NOT NULL,
  color_variation TEXT NOT NULL,
  available_bottles INTEGER NOT NULL DEFAULT 0,
  low_stock_threshold_bottles INTEGER NOT NULL DEFAULT 1,
  cost_per_bottle DECIMAL(10,2)  NOT NULL DEFAULT 0.00,
  remaining_fluid_percentage DECIMAL(5,2)  NOT NULL DEFAULT 100.00,
  low_ink_threshold DECIMAL(5,2)  NOT NULL DEFAULT 20.00,
  last_replenished_at TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT NULL,
  PRIMARY KEY (ink_id),
  CONSTRAINT fk_ink_printer
    FOREIGN KEY (printer_id) REFERENCES printers (printer_id)
    ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS bond_paper_stocks (
  paper_stock_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  paper_size_dimension TEXT NOT NULL,
  remaining_reams DECIMAL(8,2)  NOT NULL DEFAULT 0.00,
  unopened_reams INTEGER NOT NULL DEFAULT 0,
  low_stock_threshold_reams DECIMAL(8,2)  NOT NULL DEFAULT 2.00,
  average_expense_cost DECIMAL(10,2)  NOT NULL DEFAULT 0.00,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT NULL,
  PRIMARY KEY (paper_stock_id),
  CONSTRAINT uq_paper_size UNIQUE (paper_size_dimension)
);

CREATE TABLE IF NOT EXISTS paper_replenishments (
  replenishment_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  paper_stock_id INTEGER NOT NULL,
  recorded_by_user_id BIGINT DEFAULT NULL,
  replenishment_date TIMESTAMP NOT NULL,
  quantity_added_reams DECIMAL(8,2)  NOT NULL,
  expense_cost DECIMAL(10,2)  NOT NULL DEFAULT 0.00,
  notes VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (replenishment_id),
  CONSTRAINT fk_replenishment_stock
    FOREIGN KEY (paper_stock_id) REFERENCES bond_paper_stocks (paper_stock_id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_replenishment_recorder
    FOREIGN KEY (recorded_by_user_id) REFERENCES users (user_id)
    ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS print_cash_payments (
  print_cash_payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  request_id BIGINT NOT NULL,
  amount_paid DECIMAL(10,2)  NOT NULL,
  received_by_user_id BIGINT NULL,
  received_at TIMESTAMP NOT NULL,
  notes VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (print_cash_payment_id),
  CONSTRAINT uq_print_cash_request UNIQUE (request_id),
  CONSTRAINT fk_print_cash_request FOREIGN KEY (request_id) REFERENCES print_requests (request_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_print_cash_receiver FOREIGN KEY (received_by_user_id) REFERENCES users (user_id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS ink_stock_movements (
  ink_stock_movement_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  ink_id INTEGER NOT NULL,
  movement_type TEXT NOT NULL,
  activity_code VARCHAR(32) NOT NULL DEFAULT 'Legacy',
  quantity_bottles INTEGER NOT NULL,
  unit_cost_per_bottle DECIMAL(10,2)  NOT NULL DEFAULT 0.00,
  expense_amount DECIMAL(10,2)  NOT NULL DEFAULT 0.00,
  balance_before INTEGER NULL,
  balance_after INTEGER NULL,
  recorded_by_user_id BIGINT NULL,
  notes VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ink_stock_movement_id),
  CONSTRAINT fk_ink_movement_stock FOREIGN KEY (ink_id) REFERENCES ink_repository (ink_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_ink_movement_recorder FOREIGN KEY (recorded_by_user_id) REFERENCES users (user_id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS paper_stock_movements (
  paper_stock_movement_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  paper_stock_id INTEGER NOT NULL,
  print_request_id BIGINT NULL,
  movement_type TEXT NOT NULL,
  activity_code VARCHAR(32) NOT NULL DEFAULT 'Legacy',
  quantity_reams DECIMAL(10,4)  NOT NULL,
  unit_cost_per_ream DECIMAL(10,2)  NOT NULL DEFAULT 0.00,
  expense_amount DECIMAL(10,2)  NOT NULL DEFAULT 0.00,
  balance_before DECIMAL(10,4)  NULL,
  balance_after DECIMAL(10,4)  NULL,
  recorded_by_user_id BIGINT NULL,
  notes VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (paper_stock_movement_id),
  CONSTRAINT uq_paper_movement_request_issue UNIQUE (print_request_id,movement_type),
  CONSTRAINT fk_paper_movement_stock FOREIGN KEY (paper_stock_id) REFERENCES bond_paper_stocks (paper_stock_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_paper_movement_request FOREIGN KEY (print_request_id) REFERENCES print_requests (request_id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_paper_movement_recorder FOREIGN KEY (recorded_by_user_id) REFERENCES users (user_id) ON UPDATE CASCADE ON DELETE SET NULL
);

-- ============================================================================
-- 8. SYSTEM NOTIFICATIONS
-- ============================================================================

CREATE TABLE IF NOT EXISTS notifications (
  notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  message_title VARCHAR(150) NOT NULL,
  message_body TEXT NOT NULL,
  trigger_type TEXT NOT NULL,
  source_type VARCHAR(40) DEFAULT NULL,
  source_id BIGINT DEFAULT NULL,
  action_path VARCHAR(255) DEFAULT NULL,
  priority TEXT NOT NULL DEFAULT 'Normal',
  dedupe_key VARCHAR(191) DEFAULT NULL,
  scheduled_for TIMESTAMP DEFAULT NULL,
  delivered_at TIMESTAMP DEFAULT NULL,
  expires_at TIMESTAMP DEFAULT NULL,
  is_read INTEGER NOT NULL DEFAULT 0,
  notification_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  read_at TIMESTAMP DEFAULT NULL,
  PRIMARY KEY (notification_id),
  CONSTRAINT uq_notification_user_dedupe UNIQUE (user_id, dedupe_key),
  CONSTRAINT fk_notification_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS library_closed_days (
  closed_date DATE NOT NULL,
  reason VARCHAR(191) NOT NULL,
  created_by_user_id BIGINT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (closed_date),
  CONSTRAINT fk_library_closed_days_creator
    FOREIGN KEY (created_by_user_id) REFERENCES users (user_id)
    ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS library_operating_schedule (
  day_of_week SMALLINT NOT NULL,
  is_open INTEGER NOT NULL DEFAULT 1,
  opens_at TIME DEFAULT NULL,
  closes_at TIME DEFAULT NULL,
  updated_by_user_id BIGINT DEFAULT NULL,
  updated_at TIMESTAMP DEFAULT NULL,
  PRIMARY KEY (day_of_week),
  CONSTRAINT fk_library_schedule_updater FOREIGN KEY (updated_by_user_id) REFERENCES users (user_id) ON UPDATE CASCADE ON DELETE SET NULL
);

INSERT INTO library_operating_schedule (day_of_week,is_open,opens_at,closes_at) VALUES
  (1,1,'07:00:00','17:00:00'),(2,1,'07:00:00','17:00:00'),(3,1,'07:00:00','17:00:00'),
  (4,1,'07:00:00','17:00:00'),(5,1,'07:00:00','17:00:00'),(6,1,'07:00:00','17:00:00'),(7,0,NULL,NULL);

CREATE TABLE IF NOT EXISTS announcements (
  announcement_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  title VARCHAR(150) NOT NULL,
  message_body TEXT NOT NULL,
  priority TEXT NOT NULL DEFAULT 'Normal',
  announcement_status TEXT NOT NULL DEFAULT 'Draft',
  publish_at TIMESTAMP DEFAULT NULL,
  expires_at TIMESTAMP DEFAULT NULL,
  published_at TIMESTAMP DEFAULT NULL,
  archived_at TIMESTAMP DEFAULT NULL,
  created_by_user_id BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT NULL,
  PRIMARY KEY (announcement_id),
  CONSTRAINT fk_announcement_creator FOREIGN KEY (created_by_user_id) REFERENCES users (user_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS announcement_revisions (
  announcement_revision_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  announcement_id BIGINT NOT NULL,
  revision_number INTEGER NOT NULL,
  title_snapshot VARCHAR(150) NOT NULL,
  body_snapshot TEXT NOT NULL,
  priority_snapshot TEXT NOT NULL,
  changed_by_user_id BIGINT NOT NULL,
  change_reason VARCHAR(500) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (announcement_revision_id),
  CONSTRAINT uq_announcement_revision UNIQUE (announcement_id, revision_number),
  CONSTRAINT fk_announcement_revision_parent FOREIGN KEY (announcement_id) REFERENCES announcements (announcement_id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_announcement_revision_actor FOREIGN KEY (changed_by_user_id) REFERENCES users (user_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS admin_notifications (
  admin_notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  event_type TEXT NOT NULL,
  actor_user_id BIGINT DEFAULT NULL,
  reservation_id BIGINT DEFAULT NULL,
  borrow_transaction_id BIGINT DEFAULT NULL,
  book_title_id BIGINT DEFAULT NULL,
  message_title VARCHAR(150) NOT NULL,
  message_body VARCHAR(500) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (admin_notification_id),
  CONSTRAINT fk_admin_notifications_actor FOREIGN KEY (actor_user_id) REFERENCES users (user_id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_admin_notifications_reservation FOREIGN KEY (reservation_id) REFERENCES reservations (reservation_id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_admin_notifications_borrow FOREIGN KEY (borrow_transaction_id) REFERENCES borrow_transactions (transaction_id) ON UPDATE CASCADE ON DELETE SET NULL
);

-- Read-only compatibility ledger for integrations using queue-phase names.
CREATE OR REPLACE VIEW borrow_records AS
SELECT
  bt.transaction_id AS id,
  bt.request_group_id,
  bt.reservation_id,
  bt.user_id,
  bt.physical_copy_id,
  CASE bt.transaction_status
    WHEN 'Pending' THEN 'pending_claim'
    WHEN 'Borrowed' THEN 'active'
    WHEN 'Overdue' THEN 'overdue'
    WHEN 'Returned' THEN 'returned'
    WHEN 'Cancelled' THEN 'cancelled'
  END AS borrow_status,
  bt.borrowed_at AS borrow_date,
  bt.due_at AS due_date,
  bt.returned_at AS return_date,
  bt.cancelled_at,
  bt.created_at,
  bt.updated_at
FROM borrow_transactions bt;

-- ============================================================================
-- 9. MYSQL 5.6-COMPATIBLE BUSINESS-RULE TRIGGERS
-- MySQL 5.6 parses CHECK clauses but does not enforce them, so triggers enforce
-- the critical borrowing, due-time, and ink-percentage rules.
-- ============================================================================



-- TODO PL/pgSQL trigger (skipped)



-- TODO PL/pgSQL trigger (skipped)



-- TODO PL/pgSQL trigger (skipped)



-- TODO PL/pgSQL trigger (skipped)



-- TODO PL/pgSQL trigger (skipped)



-- TODO PL/pgSQL trigger (skipped)



-- TODO PL/pgSQL trigger (skipped)



-- TODO PL/pgSQL trigger (skipped)



-- End of schema.
SELECT 'STI Ormoc Smart Library schema created successfully.' AS schema_status;


-- Recreated indexes
CREATE INDEX IF NOT EXISTS idx_users_role_id ON users (role_id);
CREATE INDEX IF NOT EXISTS idx_users_user_role ON users (user_role);
CREATE INDEX IF NOT EXISTS idx_users_account_status ON users (account_status);
CREATE INDEX IF NOT EXISTS idx_accounts_role_status ON accounts (role, account_status);
CREATE INDEX IF NOT EXISTS idx_accounts_status ON accounts (account_status);
CREATE INDEX IF NOT EXISTS idx_student_profiles_name ON student_profiles (last_name, first_name);
CREATE INDEX IF NOT EXISTS idx_student_profiles_program_year ON student_profiles (program_strand, year_grade_level);
CREATE INDEX IF NOT EXISTS idx_auth_sessions_expires_at ON auth_sessions (expires_at);
CREATE INDEX IF NOT EXISTS idx_categories_shelf_location ON categories (shelf_location);
CREATE INDEX IF NOT EXISTS idx_categories_name_shelf ON categories (category_name, shelf_location);
CREATE INDEX IF NOT EXISTS idx_materials_category_id ON materials (category_id);
CREATE INDEX IF NOT EXISTS idx_materials_isbn ON materials (isbn);
CREATE INDEX IF NOT EXISTS idx_materials_title ON materials (title);
CREATE INDEX IF NOT EXISTS idx_materials_type_status ON materials (material_type, availability_status);
CREATE INDEX IF NOT EXISTS idx_materials_shelf_location ON materials (shelf_location);
CREATE INDEX IF NOT EXISTS idx_research_inventory_title ON research_inventory (title);
CREATE INDEX IF NOT EXISTS idx_research_inventory_year ON research_inventory (publication_year);
CREATE INDEX IF NOT EXISTS idx_research_inventory_condition_availability ON research_inventory (condition_state, availability_status);
CREATE INDEX IF NOT EXISTS idx_research_inventory_active_search ON research_inventory (availability_status, publication_year, condition_state);
CREATE INDEX IF NOT EXISTS idx_research_inventory_lifecycle ON research_inventory (lifecycle_status, availability_status, publication_year);
CREATE INDEX IF NOT EXISTS idx_research_inventory_shelf ON research_inventory (shelf_location);
CREATE INDEX IF NOT EXISTS idx_research_inventory_last_audited ON research_inventory (last_audited_at);
CREATE INDEX IF NOT EXISTS idx_research_inventory_archived_by ON research_inventory (archived_by_user_id);
CREATE INDEX IF NOT EXISTS idx_research_audit_item_date ON research_inventory_audit_events (research_inventory_id, created_at);
CREATE INDEX IF NOT EXISTS idx_research_audit_barcode_date ON research_inventory_audit_events (barcode_snapshot, created_at);
CREATE INDEX IF NOT EXISTS idx_research_audit_type_date ON research_inventory_audit_events (event_type, created_at);
CREATE INDEX IF NOT EXISTS idx_borrow_user_status ON borrow_transactions (user_id, transaction_status);
CREATE INDEX IF NOT EXISTS idx_borrow_material_status ON borrow_transactions (material_id, transaction_status);
CREATE INDEX IF NOT EXISTS idx_borrow_copy_status ON borrow_transactions (physical_copy_id, transaction_status);
CREATE INDEX IF NOT EXISTS idx_borrow_request_group ON borrow_transactions (request_group_id, transaction_status);
CREATE INDEX IF NOT EXISTS idx_borrow_user_queue ON borrow_transactions (user_id, transaction_status, created_at, transaction_id);
CREATE INDEX IF NOT EXISTS idx_borrow_due_at ON borrow_transactions (due_at);
CREATE INDEX IF NOT EXISTS idx_borrow_lost_status ON borrow_transactions (user_id, lost_confirmed_at, transaction_status);
CREATE INDEX IF NOT EXISTS idx_borrow_processed_by ON borrow_transactions (processed_by_user_id);
CREATE INDEX IF NOT EXISTS idx_borrow_cancelled_by ON borrow_transactions (cancelled_by_user_id, cancelled_at);
CREATE INDEX IF NOT EXISTS idx_reservation_status_reserved ON reservations (reservation_status, reserved_at, reservation_id);
CREATE INDEX IF NOT EXISTS idx_reservation_user_status ON reservations (user_id, reservation_status, reserved_at);
CREATE INDEX IF NOT EXISTS idx_reservation_material_status ON reservations (material_id, reservation_status, reserved_at);
CREATE INDEX IF NOT EXISTS idx_reservation_pickup_expiry ON reservations (reservation_status, pickup_deadline);
CREATE INDEX IF NOT EXISTS idx_reservation_accession_status ON reservations (accession_id, reservation_status);
CREATE INDEX IF NOT EXISTS idx_reservation_title_queue ON reservations (book_title_id, reservation_status, queue_position, reserved_at);
CREATE INDEX IF NOT EXISTS idx_reservation_assigned_copy ON reservations (assigned_physical_copy_id, reservation_status);
CREATE INDEX IF NOT EXISTS idx_fines_user_payment ON fines (user_id, payment_status);
CREATE INDEX IF NOT EXISTS idx_fines_applied_date ON fines (applied_date);
CREATE INDEX IF NOT EXISTS idx_fines_type_status_date ON fines (fine_type,payment_status,applied_date);
CREATE INDEX IF NOT EXISTS idx_fine_policy_active_effective ON fine_policy_versions (is_active,effective_from,effective_until);
CREATE INDEX IF NOT EXISTS idx_fine_infraction_incident ON fine_infractions (incident_at,category);
CREATE INDEX IF NOT EXISTS idx_fine_receipt_user_date ON fine_payment_receipts (user_id,received_at);
CREATE INDEX IF NOT EXISTS idx_fine_receipt_status_date ON fine_payment_receipts (receipt_status,received_at);
CREATE INDEX IF NOT EXISTS idx_fine_allocation_fine ON fine_payment_allocations (fine_id,fine_payment_receipt_id);
CREATE INDEX IF NOT EXISTS idx_fine_allocation_lost ON fine_payment_allocations (lost_book_report_id,fine_payment_receipt_id);
CREATE INDEX IF NOT EXISTS idx_fine_adjustment_fine_date ON fine_adjustments (fine_id,adjusted_at);
CREATE INDEX IF NOT EXISTS idx_fine_adjustment_actor_date ON fine_adjustments (adjusted_by_user_id,adjusted_at);
CREATE INDEX IF NOT EXISTS idx_clearance_standing ON clearance_statuses (standing_status);
CREATE INDEX IF NOT EXISTS idx_clearance_reviewer ON clearance_statuses (reviewed_by_user_id);
CREATE INDEX IF NOT EXISTS idx_clearance_override_user_active ON clearance_overrides (user_id, revoked_at, expires_at, applied_at);
CREATE INDEX IF NOT EXISTS idx_lost_book_user_status ON lost_book_reports (user_id, report_status, payment_status);
CREATE INDEX IF NOT EXISTS idx_academic_terms_dates ON academic_terms (starts_on, ends_on);
CREATE INDEX IF NOT EXISTS idx_academic_terms_active_dates ON academic_terms (is_active, starts_on, ends_on);
CREATE INDEX IF NOT EXISTS idx_attendance_user_date ON attendance_logs (user_id, attendance_date);
CREATE INDEX IF NOT EXISTS idx_attendance_date_time ON attendance_logs (attendance_date, time_in);
CREATE INDEX IF NOT EXISTS idx_attendance_reason ON attendance_logs (reason_for_visit);
CREATE INDEX IF NOT EXISTS idx_attendance_presence ON attendance_logs (attendance_date, time_out, user_id);
CREATE INDEX IF NOT EXISTS idx_attendance_purpose_date ON attendance_logs (reason_for_visit, attendance_date);
CREATE INDEX IF NOT EXISTS idx_print_user_status ON print_requests (user_id, job_status);
CREATE INDEX IF NOT EXISTS idx_print_queue ON print_requests (job_status, created_at);
CREATE INDEX IF NOT EXISTS idx_print_processed_by ON print_requests (processed_by_user_id);
CREATE INDEX IF NOT EXISTS idx_print_service_accepting ON printing_service_settings (accepting_requests);
CREATE INDEX IF NOT EXISTS idx_print_service_updated_by ON printing_service_settings (updated_by_user_id);
CREATE INDEX IF NOT EXISTS idx_print_download_request_date ON print_file_download_audit (request_id,downloaded_at);
CREATE INDEX IF NOT EXISTS idx_print_download_user_date ON print_file_download_audit (downloaded_by_user_id,downloaded_at);
CREATE INDEX IF NOT EXISTS idx_ink_printer ON ink_repository (printer_id);
CREATE INDEX IF NOT EXISTS idx_ink_color ON ink_repository (color_variation);
CREATE INDEX IF NOT EXISTS idx_paper_replenishment_stock_date ON paper_replenishments (paper_stock_id, replenishment_date);
CREATE INDEX IF NOT EXISTS idx_paper_replenishment_recorder ON paper_replenishments (recorded_by_user_id);
CREATE INDEX IF NOT EXISTS idx_print_cash_received_at ON print_cash_payments (received_at);
CREATE INDEX IF NOT EXISTS idx_print_cash_received_date ON print_cash_payments (received_by_user_id,received_at);
CREATE INDEX IF NOT EXISTS idx_ink_movement_stock_date ON ink_stock_movements (ink_id,created_at);
CREATE INDEX IF NOT EXISTS idx_ink_movement_type_date ON ink_stock_movements (movement_type,created_at);
CREATE INDEX IF NOT EXISTS idx_ink_activity_date ON ink_stock_movements (activity_code,created_at);
CREATE INDEX IF NOT EXISTS idx_paper_movement_stock_date ON paper_stock_movements (paper_stock_id,created_at);
CREATE INDEX IF NOT EXISTS idx_paper_movement_type_date ON paper_stock_movements (movement_type,created_at);
CREATE INDEX IF NOT EXISTS idx_paper_activity_date ON paper_stock_movements (activity_code,created_at);
CREATE INDEX IF NOT EXISTS idx_notification_user_read ON notifications (user_id, is_read);
CREATE INDEX IF NOT EXISTS idx_notification_timestamp ON notifications (notification_timestamp);
CREATE INDEX IF NOT EXISTS idx_notification_trigger ON notifications (trigger_type);
CREATE INDEX IF NOT EXISTS idx_notification_schedule ON notifications (scheduled_for, delivered_at);
CREATE INDEX IF NOT EXISTS idx_notification_source ON notifications (source_type, source_id);
CREATE INDEX IF NOT EXISTS idx_library_closed_days_creator ON library_closed_days (created_by_user_id);
CREATE INDEX IF NOT EXISTS idx_announcement_status_publish ON announcements (announcement_status, publish_at);
CREATE INDEX IF NOT EXISTS idx_admin_notifications_created ON admin_notifications (created_at, admin_notification_id);
CREATE INDEX IF NOT EXISTS idx_admin_notifications_event_created ON admin_notifications (event_type, created_at);
CREATE INDEX IF NOT EXISTS idx_admin_notifications_reservation ON admin_notifications (reservation_id);
CREATE INDEX IF NOT EXISTS idx_admin_notifications_borrow ON admin_notifications (borrow_transaction_id);

CREATE TABLE IF NOT EXISTS schema_migrations (
  migration_name VARCHAR(191) PRIMARY KEY,
  checksum CHAR(64) NOT NULL,
  applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
