-- ============================================================================
-- Curated Postgres gap-fill for schema-readiness after 001 + partial 002
-- Adds tables/columns the API health check requires.
-- ============================================================================

CREATE TABLE IF NOT EXISTS barcode_sequences (
  sequence_year SMALLINT NOT NULL,
  last_value INTEGER NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (sequence_year)
);

CREATE TABLE IF NOT EXISTS inventory_audit_events (
  inventory_audit_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  physical_copy_id BIGINT NOT NULL REFERENCES physical_copies (physical_copy_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  barcode_snapshot VARCHAR(100) NOT NULL,
  event_type TEXT NOT NULL,
  previous_condition TEXT DEFAULT NULL,
  new_condition TEXT DEFAULT NULL,
  previous_availability TEXT DEFAULT NULL,
  new_availability TEXT DEFAULT NULL,
  verified_by_user_id BIGINT DEFAULT NULL REFERENCES users (user_id) ON UPDATE CASCADE ON DELETE SET NULL,
  verified_by_label VARCHAR(255) NOT NULL,
  action_reason VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_inventory_audit_copy_date ON inventory_audit_events (physical_copy_id, created_at);
CREATE INDEX IF NOT EXISTS idx_inventory_audit_barcode_date ON inventory_audit_events (barcode_snapshot, created_at);

CREATE TABLE IF NOT EXISTS print_pricing_rules (
  pricing_rule_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  print_type TEXT NOT NULL,
  paper_size TEXT NOT NULL,
  price_per_page DECIMAL(10,2) NOT NULL,
  is_active SMALLINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT NULL,
  CONSTRAINT uq_print_pricing_type_size UNIQUE (print_type, paper_size)
);

INSERT INTO print_pricing_rules (print_type, paper_size, price_per_page) VALUES
  ('Monochrome','Short',2.00),('Monochrome','A4',2.00),('Monochrome','Long',3.00),
  ('Colored','Short',5.00),('Colored','A4',5.00),('Colored','Long',7.00)
ON CONFLICT (print_type, paper_size) DO NOTHING;

CREATE TABLE IF NOT EXISTS print_status_history (
  print_status_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id BIGINT NOT NULL REFERENCES print_requests (request_id) ON UPDATE CASCADE ON DELETE CASCADE,
  from_status VARCHAR(30) DEFAULT NULL,
  to_status VARCHAR(30) NOT NULL,
  changed_by_user_id BIGINT DEFAULT NULL REFERENCES users (user_id) ON UPDATE CASCADE ON DELETE SET NULL,
  reason VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_print_history_request_date ON print_status_history (request_id, created_at);

ALTER TABLE titles ADD COLUMN IF NOT EXISTS purchase_price DECIMAL(10,2) DEFAULT NULL;
ALTER TABLE physical_copies ADD COLUMN IF NOT EXISTS qr_code_data TEXT DEFAULT NULL;
ALTER TABLE research_inventory ADD COLUMN IF NOT EXISTS title_id BIGINT DEFAULT NULL;
ALTER TABLE research_inventory ADD COLUMN IF NOT EXISTS qr_code_data TEXT DEFAULT NULL;

ALTER TABLE print_requests ADD COLUMN IF NOT EXISTS printer_id INTEGER DEFAULT NULL;
ALTER TABLE print_requests ADD COLUMN IF NOT EXISTS paper_size TEXT NOT NULL DEFAULT 'A4';
ALTER TABLE print_requests ADD COLUMN IF NOT EXISTS page_count INTEGER NOT NULL DEFAULT 1;
ALTER TABLE print_requests ADD COLUMN IF NOT EXISTS total_sheets INTEGER NOT NULL DEFAULT 1;
ALTER TABLE print_requests ADD COLUMN IF NOT EXISTS payment_status TEXT NOT NULL DEFAULT 'Unpaid';
ALTER TABLE print_requests ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;

ALTER TABLE printers ADD COLUMN IF NOT EXISTS operational_status TEXT NOT NULL DEFAULT 'Online';
ALTER TABLE printers ADD COLUMN IF NOT EXISTS status_reason VARCHAR(255) DEFAULT NULL;

-- Seed current barcode year if empty
INSERT INTO barcode_sequences (sequence_year, last_value)
VALUES (EXTRACT(YEAR FROM CURRENT_DATE)::SMALLINT, 0)
ON CONFLICT (sequence_year) DO NOTHING;
