-- ============================================================================
-- MAIN product gap-fill for MySQL migrations 033–040 → Postgres
-- Additive only: safe after 001/003/004 on an existing Supabase project.
-- Review before apply. Uses IF NOT EXISTS / guarded ALTERs where practical.
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS public;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 033 library profile
CREATE TABLE IF NOT EXISTS library_profile_settings (
  settings_id SMALLINT NOT NULL,
  library_name VARCHAR(150) NOT NULL DEFAULT 'STI Ormoc Smart Library',
  seat_capacity INTEGER NOT NULL DEFAULT 80,
  information_text VARCHAR(500) DEFAULT NULL,
  map_asset_path VARCHAR(255) DEFAULT NULL,
  updated_by_user_id BIGINT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT NULL,
  PRIMARY KEY (settings_id),
  CONSTRAINT fk_library_profile_updater
    FOREIGN KEY (updated_by_user_id) REFERENCES users (user_id)
    ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_library_profile_updater ON library_profile_settings (updated_by_user_id);

INSERT INTO library_profile_settings (settings_id, library_name, seat_capacity, information_text)
VALUES (1, 'STI Ormoc Smart Library', 80, 'Borrow books, access research, request printing, and study in the library.')
ON CONFLICT (settings_id) DO NOTHING;

-- 034 notification soft-delete
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP DEFAULT NULL;
CREATE INDEX IF NOT EXISTS idx_notification_user_deleted
  ON notifications (user_id, deleted_at, notification_timestamp);

-- 035 floor plans
CREATE TABLE IF NOT EXISTS floor_plan_shelves (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  label VARCHAR(100) NOT NULL,
  column_count SMALLINT NOT NULL DEFAULT 3,
  row_count SMALLINT NOT NULL DEFAULT 5,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL,
  PRIMARY KEY (id),
  CONSTRAINT uq_floor_shelf_label UNIQUE (label)
);

CREATE TABLE IF NOT EXISTS floor_plan_state (
  id SMALLINT NOT NULL,
  revision INTEGER NOT NULL DEFAULT 0,
  draft TEXT NOT NULL,
  published TEXT NULL,
  updated_at TIMESTAMP NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS floor_plan_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  layout TEXT NOT NULL,
  published_by_account_id BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_floor_version_actor
    FOREIGN KEY (published_by_account_id) REFERENCES accounts(account_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS floor_plan_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  account_id BIGINT NOT NULL,
  event_type VARCHAR(40) NOT NULL,
  details TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_floor_event_actor
    FOREIGN KEY (account_id) REFERENCES accounts(account_id) ON DELETE RESTRICT
);

INSERT INTO floor_plan_shelves (label)
SELECT DISTINCT TRIM(shelf_location) FROM physical_copies
WHERE TRIM(COALESCE(shelf_location,'')) <> ''
ON CONFLICT (label) DO NOTHING;

INSERT INTO floor_plan_shelves (label)
SELECT DISTINCT TRIM(shelf_location) FROM categories
WHERE TRIM(COALESCE(shelf_location,'')) <> ''
ON CONFLICT (label) DO NOTHING;

INSERT INTO floor_plan_shelves (label)
SELECT DISTINCT TRIM(shelf_location) FROM research_inventory
WHERE TRIM(COALESCE(shelf_location,'')) <> ''
ON CONFLICT (label) DO NOTHING;

INSERT INTO floor_plan_state (id, draft)
VALUES (1, '{"areas":[{"id":"main","name":"Main Library","width":1200,"height":800,"background":null}],"objects":[]}')
ON CONFLICT (id) DO NOTHING;

-- 037 category shelf authority (data sync; MySQL <=> becomes IS DISTINCT FROM)
UPDATE physical_copies pc
SET shelf_location = c.shelf_location,
    updated_at = NOW()
FROM titles t
JOIN categories c ON c.category_id = t.category_id
JOIN floor_plan_shelves s ON s.label = c.shelf_location
WHERE t.title_id = pc.title_id
  AND t.record_type = 'Book'
  AND t.lifecycle_status = 'Active'
  AND pc.lifecycle_status = 'Active'
  AND pc.shelf_location IS DISTINCT FROM c.shelf_location;

UPDATE materials m
SET shelf_location = c.shelf_location,
    updated_at = NOW()
FROM categories c
JOIN floor_plan_shelves s ON s.label = c.shelf_location
WHERE c.category_id = m.category_id
  AND m.shelf_location IS DISTINCT FROM c.shelf_location;

UPDATE research_inventory ri
SET shelf_location = c.shelf_location,
    updated_at = NOW(),
    row_version = ri.row_version + 1
FROM titles t
JOIN categories c ON c.category_id = t.category_id
JOIN floor_plan_shelves s ON s.label = c.shelf_location
WHERE t.title_id = ri.title_id
  AND t.record_type = 'Research/Thesis'
  AND t.lifecycle_status = 'Active'
  AND ri.lifecycle_status = 'Active'
  AND ri.shelf_location IS DISTINCT FROM c.shelf_location;

-- 038 shelf grid (columns may already exist on fresh floor_plan_shelves create above)
ALTER TABLE categories ADD COLUMN IF NOT EXISTS shelf_column SMALLINT NOT NULL DEFAULT 1;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS shelf_row SMALLINT NOT NULL DEFAULT 1;
ALTER TABLE physical_copies ADD COLUMN IF NOT EXISTS shelf_column SMALLINT NOT NULL DEFAULT 1;
ALTER TABLE physical_copies ADD COLUMN IF NOT EXISTS shelf_row SMALLINT NOT NULL DEFAULT 1;
ALTER TABLE research_inventory ADD COLUMN IF NOT EXISTS shelf_column SMALLINT NOT NULL DEFAULT 1;
ALTER TABLE research_inventory ADD COLUMN IF NOT EXISTS shelf_row SMALLINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS idx_physical_copies_shelf_grid
  ON physical_copies (shelf_location, shelf_column, shelf_row);
CREATE INDEX IF NOT EXISTS idx_research_inventory_shelf_grid
  ON research_inventory (shelf_location, shelf_column, shelf_row);

-- 039 attendance QR + capacity
CREATE TABLE IF NOT EXISTS attendance_qr_credentials (
  credential_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  public_id VARCHAR(40) NOT NULL,
  secret_hash BYTEA NOT NULL,
  credential_version INTEGER NOT NULL DEFAULT 1,
  credential_status TEXT NOT NULL DEFAULT 'Active',
  issued_at TIMESTAMP NOT NULL,
  last_used_at TIMESTAMP DEFAULT NULL,
  revoked_at TIMESTAMP DEFAULT NULL,
  updated_at TIMESTAMP DEFAULT NULL,
  PRIMARY KEY (credential_id),
  CONSTRAINT uq_attendance_qr_user UNIQUE (user_id),
  CONSTRAINT uq_attendance_qr_public_id UNIQUE (public_id),
  CONSTRAINT fk_attendance_qr_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_attendance_qr_status
  ON attendance_qr_credentials (credential_status, public_id);

ALTER TABLE attendance_logs ADD COLUMN IF NOT EXISTS checked_in_at TIMESTAMP DEFAULT NULL;
ALTER TABLE attendance_logs ADD COLUMN IF NOT EXISTS checked_out_at TIMESTAMP DEFAULT NULL;
ALTER TABLE attendance_logs ADD COLUMN IF NOT EXISTS qr_credential_id BIGINT DEFAULT NULL;
ALTER TABLE attendance_logs ADD COLUMN IF NOT EXISTS scan_method TEXT NOT NULL DEFAULT 'Manual';
ALTER TABLE attendance_logs ADD COLUMN IF NOT EXISTS checked_in_by_user_id BIGINT DEFAULT NULL;
ALTER TABLE attendance_logs ADD COLUMN IF NOT EXISTS checked_out_by_user_id BIGINT DEFAULT NULL;
ALTER TABLE attendance_logs ADD COLUMN IF NOT EXISTS entry_request_id VARCHAR(64) DEFAULT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_attendance_entry_request
  ON attendance_logs (entry_request_id);
CREATE INDEX IF NOT EXISTS idx_attendance_checked_in_at ON attendance_logs (checked_in_at);
CREATE INDEX IF NOT EXISTS idx_attendance_open_visit
  ON attendance_logs (attendance_date, user_id, checked_out_at);
CREATE INDEX IF NOT EXISTS idx_attendance_qr_credential ON attendance_logs (qr_credential_id);
CREATE INDEX IF NOT EXISTS idx_attendance_checkin_staff ON attendance_logs (checked_in_by_user_id);
CREATE INDEX IF NOT EXISTS idx_attendance_checkout_staff ON attendance_logs (checked_out_by_user_id);

UPDATE attendance_logs
   SET checked_in_at = (attendance_date::timestamp + time_in),
       checked_out_at = CASE
         WHEN time_out IS NULL THEN NULL
         ELSE (attendance_date::timestamp + time_out)
       END
 WHERE checked_in_at IS NULL;

CREATE TABLE IF NOT EXISTS library_capacity_changes (
  capacity_change_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  previous_capacity INTEGER NOT NULL,
  new_capacity INTEGER NOT NULL,
  change_reason VARCHAR(255) NOT NULL,
  changed_by_user_id BIGINT DEFAULT NULL,
  changed_at TIMESTAMP NOT NULL,
  PRIMARY KEY (capacity_change_id),
  CONSTRAINT fk_capacity_changes_actor
    FOREIGN KEY (changed_by_user_id) REFERENCES users (user_id)
    ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_capacity_changes_date ON library_capacity_changes (changed_at);
CREATE INDEX IF NOT EXISTS idx_capacity_changes_actor ON library_capacity_changes (changed_by_user_id);

-- 040 printing digital receipts
CREATE TABLE IF NOT EXISTS print_payment_receipts (
  print_receipt_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  print_cash_payment_id BIGINT NOT NULL,
  request_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  receipt_number VARCHAR(32) NOT NULL,
  verification_code VARCHAR(16) NOT NULL,
  receipt_status TEXT NOT NULL DEFAULT 'Issued',
  student_name_snapshot VARCHAR(150) NOT NULL,
  school_id_snapshot VARCHAR(30) NOT NULL,
  file_name_snapshot VARCHAR(255) NOT NULL,
  page_count_snapshot INTEGER NOT NULL,
  copies_snapshot INTEGER NOT NULL,
  total_sheets_snapshot INTEGER NOT NULL,
  print_type_snapshot TEXT NOT NULL,
  paper_size_snapshot TEXT NOT NULL,
  amount_received DECIMAL(10,2) NOT NULL,
  payment_method TEXT NOT NULL DEFAULT 'Cash',
  received_by_user_id BIGINT DEFAULT NULL,
  received_by_name_snapshot VARCHAR(150) NOT NULL,
  received_at TIMESTAMP NOT NULL,
  reversed_by_user_id BIGINT DEFAULT NULL,
  reversed_at TIMESTAMP DEFAULT NULL,
  reversal_reason VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (print_receipt_id),
  CONSTRAINT uq_print_receipt_payment UNIQUE (print_cash_payment_id),
  CONSTRAINT uq_print_receipt_request UNIQUE (request_id),
  CONSTRAINT uq_print_receipt_number UNIQUE (receipt_number),
  CONSTRAINT uq_print_receipt_verification UNIQUE (verification_code),
  CONSTRAINT fk_print_receipt_payment
    FOREIGN KEY (print_cash_payment_id) REFERENCES print_cash_payments (print_cash_payment_id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_print_receipt_request
    FOREIGN KEY (request_id) REFERENCES print_requests (request_id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_print_receipt_user
    FOREIGN KEY (user_id) REFERENCES users (user_id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_print_receipt_receiver
    FOREIGN KEY (received_by_user_id) REFERENCES users (user_id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_print_receipt_reverser
    FOREIGN KEY (reversed_by_user_id) REFERENCES users (user_id)
    ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_print_receipt_user_date ON print_payment_receipts (user_id, received_at);
CREATE INDEX IF NOT EXISTS idx_print_receipt_status_date ON print_payment_receipts (receipt_status, received_at);

INSERT INTO print_payment_receipts (
  print_cash_payment_id, request_id, user_id, receipt_number, verification_code,
  student_name_snapshot, school_id_snapshot, file_name_snapshot, page_count_snapshot,
  copies_snapshot, total_sheets_snapshot, print_type_snapshot, paper_size_snapshot,
  amount_received, payment_method, received_by_user_id, received_by_name_snapshot, received_at
)
SELECT
  p.print_cash_payment_id,
  p.request_id,
  pr.user_id,
  'PR-' || to_char(p.received_at, 'YYYYMMDD') || '-' || lpad(p.print_cash_payment_id::text, 6, '0'),
  upper(substr(encode(digest('PRINT-' || p.print_cash_payment_id::text || '-' || pr.user_id::text || '-' || p.received_at::text, 'sha256'), 'hex'), 1, 16)),
  u.full_name,
  u.school_id,
  pr.file_name,
  pr.page_count,
  pr.number_of_copies,
  pr.total_sheets,
  pr.print_type,
  pr.paper_size,
  p.amount_paid,
  'Cash',
  p.received_by_user_id,
  COALESCE(staff.full_name, 'Authorized library personnel'),
  p.received_at
FROM print_cash_payments p
INNER JOIN print_requests pr ON pr.request_id = p.request_id
INNER JOIN users u ON u.user_id = pr.user_id
LEFT JOIN users staff ON staff.user_id = p.received_by_user_id
ON CONFLICT (print_cash_payment_id) DO NOTHING;
