-- Additive gaps found while reconciling the fully migrated MySQL 040 schema
-- with the live Supabase project. Keep existing hosted rows and IDs intact.

ALTER TABLE categories ADD COLUMN IF NOT EXISTS description TEXT;

CREATE TABLE IF NOT EXISTS physical_copy_asset_code_history (
  asset_code_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  physical_copy_id BIGINT NULL,
  material_id BIGINT NULL,
  title_id BIGINT NOT NULL,
  accession_number VARCHAR(100) NOT NULL,
  previous_barcode VARCHAR(100) NOT NULL,
  replacement_barcode VARCHAR(100) NOT NULL,
  replaced_at TIMESTAMP NOT NULL,
  CONSTRAINT uq_asset_code_history_replacement UNIQUE (replacement_barcode),
  CONSTRAINT fk_asset_code_history_copy FOREIGN KEY (physical_copy_id)
    REFERENCES physical_copies (physical_copy_id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_asset_code_history_title FOREIGN KEY (title_id)
    REFERENCES titles (title_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_asset_code_history_previous
  ON physical_copy_asset_code_history (previous_barcode);
CREATE INDEX IF NOT EXISTS idx_asset_code_history_copy_date
  ON physical_copy_asset_code_history (physical_copy_id, replaced_at);
CREATE INDEX IF NOT EXISTS idx_asset_code_history_title
  ON physical_copy_asset_code_history (title_id);
