-- Phase 3: retain archive attribution and published floor-plan image history.
ALTER TABLE titles ADD COLUMN IF NOT EXISTS archived_by_account_id BIGINT REFERENCES accounts(account_id);
CREATE INDEX IF NOT EXISTS idx_titles_archived_by ON titles(archived_by_account_id);

CREATE TABLE IF NOT EXISTS floor_plan_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  storage_path VARCHAR(255) NOT NULL UNIQUE,
  original_name VARCHAR(255) NOT NULL,
  mime_type VARCHAR(50) NOT NULL,
  uploaded_by_account_id BIGINT NOT NULL REFERENCES accounts(account_id),
  uploaded_at TIMESTAMP NOT NULL DEFAULT NOW(),
  is_current BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_floor_plan_current_image ON floor_plan_images(is_current) WHERE is_current = TRUE;
CREATE INDEX IF NOT EXISTS idx_floor_plan_images_uploaded ON floor_plan_images(uploaded_at DESC);
