-- Phase 2 A1: keep account decisions and invalidate previously issued credentials.
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS auth_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE users ADD COLUMN IF NOT EXISTS auth_version INTEGER NOT NULL DEFAULT 1;

CREATE TABLE IF NOT EXISTS account_management_events (
  event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id BIGINT NOT NULL REFERENCES accounts(account_id),
  actor_account_id BIGINT NOT NULL REFERENCES accounts(account_id),
  action_code VARCHAR(30) NOT NULL,
  previous_status VARCHAR(20),
  new_status VARCHAR(20),
  changed_fields VARCHAR(255),
  reason VARCHAR(500) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_account_management_events_account ON account_management_events(account_id, created_at DESC);
