-- Phase 2 A6: optional, versioned supplier quotations. Apply only after review.
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('book-quotations', 'book-quotations', false, 5242880, ARRAY['application/pdf', 'image/jpeg', 'image/png'])
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS book_quotations (
  quotation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title_id BIGINT NOT NULL REFERENCES titles(title_id) ON DELETE RESTRICT,
  storage_path VARCHAR(500) NOT NULL UNIQUE,
  original_name VARCHAR(255) NOT NULL,
  mime_type VARCHAR(40) NOT NULL,
  quoted_amount DECIMAL(10,2) NOT NULL CHECK (quoted_amount > 0),
  uploaded_by_user_id BIGINT NULL REFERENCES users(user_id) ON DELETE SET NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_book_quotations_title_latest ON book_quotations(title_id, quotation_id DESC);
ALTER TABLE lost_book_reports ADD COLUMN IF NOT EXISTS quotation_id BIGINT NULL REFERENCES book_quotations(quotation_id) ON DELETE RESTRICT;
ALTER TABLE lost_book_reports ADD COLUMN IF NOT EXISTS charge_resolution VARCHAR(24) NOT NULL DEFAULT 'Awaiting Review';
ALTER TABLE lost_book_reports ADD COLUMN IF NOT EXISTS resolution_reason VARCHAR(500) NULL;
UPDATE lost_book_reports SET charge_resolution=CASE WHEN replacement_charge>0 THEN 'Quoted' ELSE 'Awaiting Quotation' END
WHERE report_status='Confirmed' AND charge_resolution='Awaiting Review';
