-- Phase 2 A10: separate invoice ledger; historical payment receipts are untouched.
ALTER TABLE print_payment_receipts ADD COLUMN IF NOT EXISTS document_label VARCHAR(24) NULL;
ALTER TABLE fine_payment_receipts ADD COLUMN IF NOT EXISTS document_label VARCHAR(24) NULL;
UPDATE print_payment_receipts SET document_label='Legacy Receipt' WHERE document_label IS NULL;
UPDATE fine_payment_receipts SET document_label='Legacy Receipt' WHERE document_label IS NULL;
ALTER TABLE print_payment_receipts ALTER COLUMN document_label SET DEFAULT 'Payment Record';
ALTER TABLE fine_payment_receipts ALTER COLUMN document_label SET DEFAULT 'Payment Record';
ALTER TABLE print_payment_receipts ALTER COLUMN document_label SET NOT NULL;
ALTER TABLE fine_payment_receipts ALTER COLUMN document_label SET NOT NULL;
CREATE TABLE IF NOT EXISTS invoice_setup (
  settings_id SMALLINT PRIMARY KEY CHECK (settings_id=1),
  issuer_name VARCHAR(255) NOT NULL DEFAULT '',
  issuer_address TEXT NOT NULL DEFAULT '',
  issuer_tin VARCHAR(50) NOT NULL DEFAULT '',
  authority_reference VARCHAR(100) NOT NULL DEFAULT '',
  serial_prefix VARCHAR(20) NOT NULL DEFAULT 'INV-',
  serial_start BIGINT NOT NULL DEFAULT 1,
  serial_end BIGINT NOT NULL DEFAULT 0,
  next_serial BIGINT NOT NULL DEFAULT 1,
  print_classification VARCHAR(30) NOT NULL DEFAULT 'Unclassified',
  fine_classification VARCHAR(30) NOT NULL DEFAULT 'Unclassified',
  approved BOOLEAN NOT NULL DEFAULT FALSE,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO invoice_setup(settings_id) VALUES (1) ON CONFLICT (settings_id) DO NOTHING;
CREATE TABLE IF NOT EXISTS customer_invoices (
  invoice_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_type VARCHAR(30) NOT NULL,
  source_id BIGINT NOT NULL,
  revision INTEGER NOT NULL DEFAULT 1,
  invoice_number VARCHAR(50) NOT NULL UNIQUE,
  issuer_name VARCHAR(255) NOT NULL,
  issuer_address TEXT NOT NULL,
  issuer_tin VARCHAR(50) NOT NULL,
  authority_reference VARCHAR(100) NOT NULL,
  customer_name VARCHAR(255) NOT NULL,
  customer_school_id VARCHAR(60) NOT NULL,
  description VARCHAR(500) NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'Issued',
  issued_by_user_id BIGINT NULL REFERENCES users(user_id) ON DELETE SET NULL,
  issued_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  voided_by_user_id BIGINT NULL REFERENCES users(user_id) ON DELETE SET NULL,
  voided_at TIMESTAMP NULL,
  void_reason VARCHAR(500) NULL,
  UNIQUE (source_type, source_id, revision),
  CHECK (source_type IN ('Printing', 'Fine Collection')),
  CHECK (status IN ('Issued','Voided'))
);
