-- Phase 6: pending school-email registration and restricted Staff role.
INSERT INTO roles (role_name, description) VALUES
  ('Library Staff', 'Restricted circulation, reservations, printing, attendance and announcement access')
ON CONFLICT (role_name) DO NOTHING;

CREATE TABLE IF NOT EXISTS registration_requests (
  request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(191) NOT NULL UNIQUE,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  program_strand VARCHAR(150),
  year_grade_level VARCHAR(100),
  requested_role VARCHAR(20) NOT NULL CHECK (requested_role IN ('Student', 'Faculty', 'Librarian', 'Staff')),
  password_hash VARCHAR(255),
  status VARCHAR(24) NOT NULL DEFAULT 'PendingEmail' CHECK (status IN ('PendingEmail', 'PendingApproval', 'Rejected', 'Completed')),
  code_hash CHAR(64),
  code_expires_at TIMESTAMPTZ,
  code_sent_at TIMESTAMPTZ,
  code_attempts SMALLINT NOT NULL DEFAULT 0,
  email_verified_at TIMESTAMPTZ,
  reviewed_by_account_id BIGINT REFERENCES accounts(account_id),
  reviewed_at TIMESTAMPTZ,
  review_reason VARCHAR(500),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_registration_requests_status ON registration_requests(status, created_at);

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('profile-avatars', 'profile-avatars', false, 2097152, ARRAY['image/png','image/jpeg','image/webp'])
ON CONFLICT (id) DO UPDATE SET public = false, file_size_limit = 2097152,
  allowed_mime_types = ARRAY['image/png','image/jpeg','image/webp'];

CREATE TABLE IF NOT EXISTS profile_avatar_submissions (
  submission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id BIGINT NOT NULL REFERENCES accounts(account_id),
  storage_path VARCHAR(255) NOT NULL UNIQUE,
  mime_type VARCHAR(30) NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending','Approved','Rejected')),
  submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  reviewed_by_account_id BIGINT REFERENCES accounts(account_id),
  reviewed_at TIMESTAMPTZ,
  review_reason VARCHAR(500)
);
CREATE INDEX IF NOT EXISTS idx_profile_avatars_account ON profile_avatar_submissions(account_id, submitted_at DESC);
CREATE INDEX IF NOT EXISTS idx_profile_avatars_pending ON profile_avatar_submissions(status, submitted_at) WHERE status='Pending';

-- Only approved/active accounts are written to accounts/users. Historical
-- placeholder emails and account rows are deliberately untouched.
