import type { NextFunction,Request,Response } from 'express'
import { createBrandedTablePdf } from '../reports/branded-table-pdf.ts'
import { printingRepository } from './printing.repository.ts'
import { printingService } from './printing.service.ts'
import { createPrintingReceiptPdf, type PrintingReceipt } from './printing-receipt.pdf.ts'
import { parseFinanceFilters, parseQueueFilters } from './printing.validation.ts'

function actor(request:Request,response:Response){const jwt=response.locals.authenticatedUser as {schoolId?:string;role?:string}|undefined;const session=request.session?.user as {schoolId?:string;school_id?:string;role?:string}|undefined;return{schoolId:jwt?.schoolId??session?.schoolId??session?.school_id,role:jwt?.role??session?.role}}
const handle=(fn:(request:Request,response:Response)=>Promise<void>)=>(request:Request,response:Response,next:NextFunction)=>{void fn(request,response).catch(next)}
const wholeStock=(value:unknown)=>value==null?'Legacy':String(Math.trunc(Number(value)))

export const printingController={
  availability:handle(async(_request,response)=>{response.json({success:true,data:await printingService.serviceStatus()})}),
  serviceStatus:handle(async(_request,response)=>{response.json({success:true,data:await printingService.serviceStatus()})}),
  setServiceStatus:handle(async(request,response)=>{response.json({success:true,message:'Printing service availability updated.',data:await printingService.setServiceStatus(actor(request,response),request.body)})}),
  pricing:handle(async(_request,response)=>{response.json({success:true,data:await printingService.pricing()})}),
  mine:handle(async(request,response)=>{response.json({success:true,data:await printingService.ownRequests(actor(request,response))})}),
  myReceipts:handle(async(request,response)=>{response.json({success:true,data:await printingService.ownReceipts(actor(request,response))})}),
  myReceipt:handle(async(request,response)=>{response.json({success:true,data:await printingService.ownReceipt(actor(request,response),request.params.id)})}),
  myReceiptPdf:handle(async(request,response)=>{const receipt=await printingService.ownReceipt(actor(request,response),request.params.id) as unknown as PrintingReceipt;const report=createPrintingReceiptPdf(receipt);response.status(200).set({'Content-Type':'application/pdf','Content-Disposition':`attachment; filename="${receipt.receipt_number}.pdf"`,'Cache-Control':'no-store'});report.pipe(response)}),
  submit:handle(async(request,response)=>{const data=await printingService.submit(actor(request,response),request.body,request.file);response.status(201).json({success:true,message:'Print request submitted. Pay cash at the library counter before printing starts.',data})}),
  quote:handle(async(request,response)=>{response.json({success:true,data:await printingService.quote(actor(request,response),request.body,request.file)})}),
  cancel:handle(async(request,response)=>{response.json({success:true,message:'The pending print request was cancelled.',data:await printingService.cancelOwn(actor(request,response),request.params.id)})}),
  summary:handle(async(_request,response)=>{response.json({success:true,data:await printingService.summary()})}),
  queue:handle(async(request,response)=>{const result=await printingService.queue(request.query as Record<string,unknown>);response.json({success:true,data:result.rows,meta:{pagination:result.pagination}})}),
  cash:handle(async(request,response)=>{response.json({success:true,message:'Cash payment recorded.',data:await printingService.recordCash(actor(request,response),request.params.id,request.body)})}),
  adminReceipt:handle(async(request,response)=>{response.json({success:true,data:await printingService.adminReceipt(actor(request,response),request.params.id)})}),
  adminReceiptPdf:handle(async(request,response)=>{const receipt=await printingService.adminReceipt(actor(request,response),request.params.id) as unknown as PrintingReceipt;const report=createPrintingReceiptPdf(receipt);response.status(200).set({'Content-Type':'application/pdf','Content-Disposition':`attachment; filename="${receipt.receipt_number}.pdf"`,'Cache-Control':'no-store'});report.pipe(response)}),
  status:handle(async(request,response)=>{response.json({success:true,message:'Print job status updated.',data:await printingService.updateStatus(actor(request,response),request.params.id,request.body)})}),
  downloadDocument:handle(async(request,response)=>{const document=await printingService.downloadDocument(actor(request,response),request.params.id,{sourceIp:request.ip,userAgent:request.get('user-agent')});response.status(200).set({'Content-Type':document.mime,'Content-Disposition':`attachment; filename*=UTF-8''${encodeURIComponent(document.fileName)}`,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}).send(document.contents)}),
  supplies:handle(async(_request,response)=>{response.json({success:true,data:await printingService.supplies()})}),
  financeSummary:handle(async(request,response)=>{response.json({success:true,data:await printingService.financeSummary(request.query as Record<string,unknown>)})}),
  financeEntries:handle(async(request,response)=>{response.json({success:true,data:await printingService.financeEntries(request.query as Record<string,unknown>)})}),
  revenueSummary:handle(async(request,response)=>{response.json({success:true,data:await printingService.revenueSummary(request.query as Record<string,unknown>)})}),
  revenueEntries:handle(async(request,response)=>{response.json({success:true,data:await printingService.revenueEntries(request.query as Record<string,unknown>)})}),
  expenseSummary:handle(async(request,response)=>{response.json({success:true,data:await printingService.expenseSummary(request.query as Record<string,unknown>)})}),
  restockHistory:handle(async(request,response)=>{response.json({success:true,data:await printingService.restockHistory(request.query as Record<string,unknown>)})}),
  stockUsageHistory:handle(async(request,response)=>{response.json({success:true,data:await printingService.stockUsageHistory(request.query as Record<string,unknown>)})}),
  reportPackage:handle(async(request,response)=>{response.json({success:true,data:await printingService.reportPackage(request.query as Record<string,unknown>)})}),
  movements:handle(async(request,response)=>{response.json({success:true,data:await printingService.movements(request.query.limit)})}),
  inkMovement:handle(async(request,response)=>{response.status(201).json({success:true,message:'Ink bottle stock updated.',data:await printingService.inkMovement(actor(request,response),request.params.id,request.body)})}),
  createInk:handle(async(request,response)=>{response.status(201).json({success:true,message:'Ink bottle stock registered.',data:await printingService.createInkStock(actor(request,response),request.body)})}),
  createPaper:handle(async(request,response)=>{response.status(201).json({success:true,message:'Bond paper stock registered.',data:await printingService.createPaperStock(actor(request,response),request.body)})}),
  updateInkThreshold:handle(async(request,response)=>{response.json({success:true,message:'Ink low-stock alert updated.',data:await printingService.updateInkThreshold(actor(request,response),request.params.id,request.body)})}),
  updatePaperThreshold:handle(async(request,response)=>{response.json({success:true,message:'Paper low-stock alert updated.',data:await printingService.updatePaperThreshold(actor(request,response),request.params.id,request.body)})}),
  paperMovement:handle(async(request,response)=>{response.status(201).json({success:true,message:'Paper stock updated.',data:await printingService.paperMovement(actor(request,response),request.params.id,request.body)})}),
  restockInk:handle(async(request,response)=>{response.status(201).json({success:true,message:'Ink bottles added successfully.',data:await printingService.restockInk(actor(request,response),request.params.id,request.body)})}),
  restockPaper:handle(async(request,response)=>{response.status(201).json({success:true,message:'Paper reams added successfully.',data:await printingService.restockPaper(actor(request,response),request.params.id,request.body)})}),
  useInkBottle:handle(async(request,response)=>{response.status(201).json({success:true,message:'One ink bottle was recorded as loaded into the printer.',data:await printingService.useInkBottle(actor(request,response),request.params.id)})}),
  openPaperReam:handle(async(request,response)=>{response.status(201).json({success:true,message:'One bond-paper ream was recorded as opened.',data:await printingService.openPaperReam(actor(request,response),request.params.id)})}),
  printReport:handle(async(request,response)=>{const filters=parseQueueFilters(request.query as Record<string,unknown>),report=createBrandedTablePdf(printingRepository.printReportRows(filters),{title:'PRINTING QUEUE REPORT',subtitle:'Cash-only printing requests and operational status',emptyMessage:'No print requests match the selected filters.',columns:[{key:'request_id',label:'REQUEST',width:65},{key:'full_name',label:'USER',width:135},{key:'school_id',label:'SCHOOL ID',width:90},{key:'file_name',label:'FILE',width:185},{key:'page_count',label:'PAGES',width:45},{key:'number_of_copies',label:'COPIES',width:45},{key:'print_type',label:'TYPE',width:70},{key:'paper_size',label:'PAPER',width:55},{key:'calculated_cost',label:'COST',width:65,format:value=>`PHP ${Number(value).toFixed(2)}`},{key:'payment_status',label:'PAYMENT',width:70},{key:'job_status',label:'STATUS',width:95},{key:'created_at',label:'SUBMITTED',width:110}]});response.status(200).set({'Content-Type':'application/pdf','Content-Disposition':'attachment; filename="smartlib-printing-report.pdf"','Cache-Control':'no-store'});report.pipe(response)}),
  supplyReport:handle(async(_request,response)=>{const generatedAt=new Intl.DateTimeFormat('en-PH',{timeZone:'Asia/Manila',dateStyle:'medium',timeStyle:'short'}).format(new Date());const report=createBrandedTablePdf(printingRepository.supplyReportRows(),{title:'CURRENT PRINT SUPPLIES STOCK',subtitle:`Snapshot generated ${generatedAt} Asia/Manila | Unopened ink bottles and paper reams`,emptyMessage:'No print supply records are available.',columns:[{key:'supply_type',label:'TYPE',width:110},{key:'name',label:'SUPPLY',width:250},{key:'available',label:'AVAILABLE',width:140},{key:'threshold',label:'LOW THRESHOLD',width:140},{key:'status',label:'STATUS',width:120}]});response.status(200).set({'Content-Type':'application/pdf','Content-Disposition':'attachment; filename="smartlib-print-supplies-current-stock.pdf"','Cache-Control':'no-store'});report.pipe(response)}),
  financeReport:handle(async(request,response)=>{const filters=parseFinanceFilters(request.query as Record<string,unknown>),summary=await printingRepository.financeSummary(filters),report=createBrandedTablePdf(printingRepository.financeReportRows(filters),{title:'PRINTING REVENUE AND EXPENSE REPORT',subtitle:`${summary.label} | Revenue PHP ${summary.revenue.toFixed(2)} | Expenses PHP ${summary.total_expenses.toFixed(2)} | ${summary.indicator} PHP ${summary.net_result.toFixed(2)}`,emptyMessage:'No revenue or restocking entries exist for this period.',columns:[{key:'entry_date',label:'DATE',width:110},{key:'entry_name',label:'ENTRY',width:230},{key:'entry_type',label:'TYPE',width:90},{key:'quantity',label:'QUANTITY',width:90},{key:'unit_cost',label:'UNIT COST',width:80,format:value=>`PHP ${Number(value).toFixed(2)}`},{key:'revenue',label:'REVENUE',width:85,format:value=>`PHP ${Number(value).toFixed(2)}`},{key:'expense',label:'EXPENSE',width:85,format:value=>`PHP ${Number(value).toFixed(2)}`},{key:'net_impact',label:'NET',width:85,format:value=>`PHP ${Number(value).toFixed(2)}`},{key:'recorded_by',label:'RECORDED BY',width:130}]});response.status(200).set({'Content-Type':'application/pdf','Content-Disposition':`attachment; filename="smartlib-print-finance-${filters.period}-${filters.date}.pdf"`,'Cache-Control':'no-store'});report.pipe(response)}),
  revenueReport:handle(async(request,response)=>{const filters=parseFinanceFilters(request.query as Record<string,unknown>),summary=await printingRepository.revenueSummary(filters),report=createBrandedTablePdf(printingRepository.revenueReportRows(filters),{title:'PRINTING REVENUE REPORT',subtitle:`${summary.label} | Paid requests ${summary.paid_requests} | Sheets ${summary.total_sheets} | Copies ${summary.total_copies} | Revenue PHP ${summary.total_revenue.toFixed(2)}`,emptyMessage:'No paid printing requests exist for this period.',columns:[{key:'received_at',label:'DATE',width:105},{key:'request_id',label:'REQUEST',width:55},{key:'full_name',label:'STUDENT',width:120},{key:'school_id',label:'SCHOOL ID',width:85},{key:'file_name',label:'FILE',width:165},{key:'print_type',label:'TYPE',width:65},{key:'paper_size',label:'PAPER',width:50},{key:'page_count',label:'PAGES',width:45},{key:'number_of_copies',label:'COPIES',width:48},{key:'total_sheets',label:'SHEETS',width:48},{key:'amount_paid',label:'REVENUE',width:75,format:value=>`PHP ${Number(value).toFixed(2)}`},{key:'received_by',label:'RECEIVED BY',width:105}]});response.status(200).set({'Content-Type':'application/pdf','Content-Disposition':`attachment; filename="smartlib-print-revenue-${filters.period}-${filters.date}.pdf"`,'Cache-Control':'no-store'});report.pipe(response)}),
  stockExpenseReport:handle(async(request,response)=>{const filters=parseFinanceFilters(request.query as Record<string,unknown>),summary=await printingRepository.expenseSummary(filters),report=createBrandedTablePdf(printingRepository.expenseReportRows(filters),{title:'PRINT SUPPLY RESTOCK EXPENSE REPORT',subtitle:`${summary.label} | Restocks ${summary.restock_entries} | Ink PHP ${summary.ink_expenses.toFixed(2)} | Paper PHP ${summary.paper_expenses.toFixed(2)} | Total expenses PHP ${summary.total_expenses.toFixed(2)}`,emptyMessage:'No restocking expenses exist for this period.',columns:[{key:'created_at',label:'DATE',width:110},{key:'supply_type',label:'TYPE',width:65},{key:'supply_name',label:'SUPPLY',width:190},{key:'quantity',label:'QUANTITY',width:65,format:wholeStock},{key:'unit',label:'UNIT',width:55},{key:'unit_cost',label:'UNIT COST',width:80,format:value=>`PHP ${Number(value).toFixed(2)}`},{key:'total_expense',label:'TOTAL COST',width:85,format:value=>`PHP ${Number(value).toFixed(2)}`},{key:'balance_before',label:'BEFORE',width:60,format:wholeStock},{key:'balance_after',label:'AFTER',width:60,format:wholeStock},{key:'recorded_by',label:'RECORDED BY',width:130}]});response.status(200).set({'Content-Type':'application/pdf','Content-Disposition':`attachment; filename="smartlib-stock-expenses-${filters.period}-${filters.date}.pdf"`,'Cache-Control':'no-store'});report.pipe(response)}),
}
